// Spanish names + FIFA codes for the 48 World Cup 2026 teams.
// Keyed by the English name TheSportsDB returns.
export const TEAM_ES: Record<string, { es: string; code: string }> = {
  "Mexico": { es: "México", code: "MEX" },
  "South Africa": { es: "Sudáfrica", code: "RSA" },
  "South Korea": { es: "Corea del Sur", code: "KOR" },
  "Czech Republic": { es: "Chequia", code: "CZE" },
  "Canada": { es: "Canadá", code: "CAN" },
  "Bosnia-Herzegovina": { es: "Bosnia y Herzegovina", code: "BIH" },
  "Bosnia and Herzegovina": { es: "Bosnia y Herzegovina", code: "BIH" },
  "Qatar": { es: "Catar", code: "QAT" },
  "Switzerland": { es: "Suiza", code: "SUI" },
  "USA": { es: "Estados Unidos", code: "USA" },
  "United States": { es: "Estados Unidos", code: "USA" },
  "Paraguay": { es: "Paraguay", code: "PAR" },
  "Australia": { es: "Australia", code: "AUS" },
  "Turkey": { es: "Turquía", code: "TUR" },
  "Türkiye": { es: "Turquía", code: "TUR" },
  "Brazil": { es: "Brasil", code: "BRA" },
  "Morocco": { es: "Marruecos", code: "MAR" },
  "Haiti": { es: "Haití", code: "HAI" },
  "Scotland": { es: "Escocia", code: "SCO" },
  "Germany": { es: "Alemania", code: "GER" },
  "Curaçao": { es: "Curazao", code: "CUW" },
  "Curacao": { es: "Curazao", code: "CUW" },
  "Ivory Coast": { es: "Costa de Marfil", code: "CIV" },
  "Ecuador": { es: "Ecuador", code: "ECU" },
  "Netherlands": { es: "Países Bajos", code: "NED" },
  "Japan": { es: "Japón", code: "JPN" },
  "Sweden": { es: "Suecia", code: "SWE" },
  "Tunisia": { es: "Túnez", code: "TUN" },
  "Belgium": { es: "Bélgica", code: "BEL" },
  "Egypt": { es: "Egipto", code: "EGY" },
  "Iran": { es: "Irán", code: "IRN" },
  "New Zealand": { es: "Nueva Zelanda", code: "NZL" },
  "Saudi Arabia": { es: "Arabia Saudí", code: "KSA" },
  "Uruguay": { es: "Uruguay", code: "URU" },
  "Spain": { es: "España", code: "ESP" },
  "Cape Verde": { es: "Cabo Verde", code: "CPV" },
  "France": { es: "Francia", code: "FRA" },
  "Senegal": { es: "Senegal", code: "SEN" },
  "Iraq": { es: "Irak", code: "IRQ" },
  "Norway": { es: "Noruega", code: "NOR" },
  "Argentina": { es: "Argentina", code: "ARG" },
  "Algeria": { es: "Argelia", code: "ALG" },
  "Austria": { es: "Austria", code: "AUT" },
  "Jordan": { es: "Jordania", code: "JOR" },
  "Portugal": { es: "Portugal", code: "POR" },
  "DR Congo": { es: "RD Congo", code: "COD" },
  "Uzbekistan": { es: "Uzbekistán", code: "UZB" },
  "Colombia": { es: "Colombia", code: "COL" },
  "England": { es: "Inglaterra", code: "ENG" },
  "Croatia": { es: "Croacia", code: "CRO" },
  "Ghana": { es: "Ghana", code: "GHA" },
  "Panama": { es: "Panamá", code: "PAN" },
};

export function translateTeam(englishName: string): { name: string; code: string | null } {
  const hit = TEAM_ES[englishName.trim()];
  return hit ? { name: hit.es, code: hit.code } : { name: englishName, code: null };
}
