// ╔══════════════════════════════════════════════════════════════════╗
// ║  Ligas y clubes del Simulador de Carrera — GENERADO, no editar     ║
// ║                                                                    ║
// ║  Regenerar:  node scripts/build-career-dataset.mjs                 ║
// ║  Para ajustar el equilibrio, edita club-ratings.ts (`rep`).         ║
// ║                                                                    ║
// ║  rep = [nacional, continental, nivel], escala 0-5.                 ║
// ╚══════════════════════════════════════════════════════════════════╝
import type { CareerLeague } from "./types";

/** 24 ligas · 479 clubes. */
export const LEAGUES: CareerLeague[] = [
  {
    id: "premier-league",
    name: "Premier League",
    country: "ENG",
    confederation: "UEFA",
    tier: 1,
    cup: "FA Cup",
    clubs: [
    { id: "manchester-united", name: "Manchester United", short: "Manchester United", abbr: "MUN", crest: "https://media.api-sports.io/football/teams/33.png", rep: [3, 3, 5] },
    { id: "newcastle-united", name: "Newcastle United", short: "Newcastle United", abbr: "NEW", crest: "https://media.api-sports.io/football/teams/34.png", rep: [1, 1, 4] },
    { id: "bournemouth", name: "Bournemouth", short: "Bournemouth", abbr: "BOU", crest: "https://media.api-sports.io/football/teams/35.png", rep: [0, 0, 4] },
    { id: "fulham", name: "Fulham", short: "Fulham", abbr: "FUL", crest: "https://media.api-sports.io/football/teams/36.png", rep: [0, 0, 3] },
    { id: "wolverhampton", name: "Wolverhampton", short: "Wolverhampton", abbr: "WOL", crest: "https://media.api-sports.io/football/teams/39.png", rep: [0, 0, 3] },
    { id: "liverpool", name: "Liverpool", short: "Liverpool", abbr: "LIV", crest: "https://media.api-sports.io/football/teams/40.png", rep: [3, 4, 5] },
    { id: "arsenal", name: "Arsenal", short: "Arsenal", abbr: "ARS", crest: "https://media.api-sports.io/football/teams/42.png", rep: [3, 4, 5] },
    { id: "burnley", name: "Burnley", short: "Burnley", abbr: "BUR", crest: "https://media.api-sports.io/football/teams/44.png", rep: [0, 0, 3] },
    { id: "everton", name: "Everton", short: "Everton", abbr: "EVE", crest: "https://media.api-sports.io/football/teams/45.png", rep: [1, 0, 4] },
    { id: "tottenham-hotspur", name: "Tottenham Hotspur", short: "Tottenham Hotspur", abbr: "TOT", crest: "https://media.api-sports.io/football/teams/47.png", rep: [1, 1, 5] },
    { id: "west-ham-united", name: "West Ham United", short: "West Ham United", abbr: "WES", crest: "https://media.api-sports.io/football/teams/48.png", rep: [0, 0, 3] },
    { id: "chelsea", name: "Chelsea", short: "Chelsea", abbr: "CHE", crest: "https://media.api-sports.io/football/teams/49.png", rep: [3, 4, 5] },
    { id: "manchester-city", name: "Manchester City", short: "Manchester City", abbr: "MCI", crest: "https://media.api-sports.io/football/teams/50.png", rep: [3, 4, 5] },
    { id: "brighton-hove-albion", name: "Brighton & Hove Albion", short: "Brighton & Hove A…", abbr: "BRI", crest: "https://media.api-sports.io/football/teams/51.png", rep: [0, 0, 4] },
    { id: "crystal-palace", name: "Crystal Palace", short: "Crystal Palace", abbr: "CRY", crest: "https://media.api-sports.io/football/teams/52.png", rep: [0, 0, 4] },
    { id: "brentford", name: "Brentford", short: "Brentford", abbr: "BRE", crest: "https://media.api-sports.io/football/teams/55.png", rep: [0, 0, 3] },
    { id: "sheffield-united", name: "Sheffield United", short: "Sheffield United", abbr: "SHE", crest: "https://media.api-sports.io/football/teams/62.png", rep: [0, 0, 3] },
    { id: "nottingham-forest", name: "Nottingham Forest", short: "Nottingham Forest", abbr: "NOT", crest: "https://media.api-sports.io/football/teams/65.png", rep: [0, 0, 4] },
    { id: "aston-villa", name: "Aston Villa", short: "Aston Villa", abbr: "AST", crest: "https://media.api-sports.io/football/teams/66.png", rep: [1, 1, 4] },
    { id: "luton-town", name: "Luton Town", short: "Luton Town", abbr: "LUT", crest: "https://media.api-sports.io/football/teams/1359.png", rep: [0, 0, 1] },
    ],
  },
  {
    id: "championship",
    name: "Championship",
    country: "ENG",
    confederation: "UEFA",
    tier: 2,
    cup: "FA Cup",
    clubs: [
    { id: "huddersfield-town", name: "Huddersfield Town", short: "Huddersfield Town", abbr: "HUD", crest: "https://media.api-sports.io/football/teams/37.png", rep: [0, 0, 1] },
    { id: "watford", name: "Watford", short: "Watford", abbr: "WAT", crest: "https://media.api-sports.io/football/teams/38.png", rep: [0, 0, 2] },
    { id: "southampton", name: "Southampton", short: "Southampton", abbr: "SOU", crest: "https://media.api-sports.io/football/teams/41.png", rep: [0, 0, 3] },
    { id: "cardiff-city", name: "Cardiff City", short: "Cardiff City", abbr: "CAR", crest: "https://media.api-sports.io/football/teams/43.png", rep: [0, 0, 1] },
    { id: "leicester-city", name: "Leicester City", short: "Leicester City", abbr: "LEI", crest: "https://media.api-sports.io/football/teams/46.png", rep: [0, 0, 2] },
    { id: "birmingham-city", name: "Birmingham City", short: "Birmingham City", abbr: "BIR", crest: "https://media.api-sports.io/football/teams/54.png", rep: [0, 0, 2] },
    { id: "bristol-city", name: "Bristol City", short: "Bristol City", abbr: "BRI", crest: "https://media.api-sports.io/football/teams/56.png", rep: [0, 0, 1] },
    { id: "ipswich-town", name: "Ipswich Town", short: "Ipswich Town", abbr: "IPS", crest: "https://media.api-sports.io/football/teams/57.png", rep: [0, 0, 3] },
    { id: "millwall", name: "Millwall", short: "Millwall", abbr: "MIL", crest: "https://media.api-sports.io/football/teams/58.png", rep: [0, 0, 2] },
    { id: "preston-north-end", name: "Preston North End", short: "Preston North End", abbr: "PRE", crest: "https://media.api-sports.io/football/teams/59.png", rep: [0, 0, 1] },
    { id: "west-bromwich-albion", name: "West Bromwich Albion", short: "West Bromwich Alb…", abbr: "WES", crest: "https://media.api-sports.io/football/teams/60.png", rep: [0, 0, 1] },
    { id: "leeds-united", name: "Leeds United", short: "Leeds United", abbr: "LEE", crest: "https://media.api-sports.io/football/teams/63.png", rep: [0, 0, 3] },
    { id: "hull-city", name: "Hull City", short: "Hull City", abbr: "HUL", crest: "https://media.api-sports.io/football/teams/64.png", rep: [0, 0, 2] },
    { id: "blackburn-rovers", name: "Blackburn Rovers", short: "Blackburn Rovers", abbr: "BLA", crest: "https://media.api-sports.io/football/teams/67.png", rep: [0, 0, 1] },
    { id: "middlesbrough", name: "Middlesbrough", short: "Middlesbrough", abbr: "MID", crest: "https://media.api-sports.io/football/teams/70.png", rep: [0, 0, 3] },
    { id: "norwich-city", name: "Norwich City", short: "Norwich City", abbr: "NOR", crest: "https://media.api-sports.io/football/teams/71.png", rep: [0, 0, 3] },
    { id: "queens-park-rangers", name: "Queens Park Rangers", short: "Queens Park Range…", abbr: "QPR", crest: "https://media.api-sports.io/football/teams/72.png", rep: [0, 0, 1] },
    { id: "rotherham-united", name: "Rotherham United", short: "Rotherham United", abbr: "ROT", crest: "https://media.api-sports.io/football/teams/73.png", rep: [0, 0, 0] },
    { id: "sheffield-wednesday", name: "Sheffield Wednesday", short: "Sheffield Wednesd…", abbr: "SHE", crest: "https://media.api-sports.io/football/teams/74.png", rep: [0, 0, 3] },
    { id: "stoke-city", name: "Stoke City", short: "Stoke City", abbr: "STO", crest: "https://media.api-sports.io/football/teams/75.png", rep: [0, 0, 2] },
    { id: "swansea-city", name: "Swansea City", short: "Swansea City", abbr: "SWA", crest: "https://media.api-sports.io/football/teams/76.png", rep: [0, 0, 2] },
    { id: "sunderland", name: "Sunderland", short: "Sunderland", abbr: "SUN", crest: "https://media.api-sports.io/football/teams/746.png", rep: [0, 0, 3] },
    { id: "coventry-city", name: "Coventry City", short: "Coventry City", abbr: "COV", crest: "https://media.api-sports.io/football/teams/1346.png", rep: [0, 0, 3] },
    { id: "plymouth-argyle", name: "Plymouth Argyle", short: "Plymouth Argyle", abbr: "PLY", crest: "https://media.api-sports.io/football/teams/1357.png", rep: [0, 0, 1] },
    ],
  },
  {
    id: "laliga",
    name: "LaLiga",
    country: "ESP",
    confederation: "UEFA",
    tier: 1,
    cup: "Copa del Rey",
    clubs: [
    { id: "fc-barcelona", name: "FC Barcelona", short: "Barcelona", abbr: "BAR", crest: "https://media.api-sports.io/football/teams/529.png", rep: [4, 4, 5] },
    { id: "atletico-de-madrid", name: "Atlético de Madrid", short: "Atlético de Madrid", abbr: "ATM", crest: "https://media.api-sports.io/football/teams/530.png", rep: [2, 2, 4] },
    { id: "athletic-club", name: "Athletic Club", short: "Athletic Club", abbr: "BIL", crest: "https://media.api-sports.io/football/teams/531.png", rep: [1, 1, 3] },
    { id: "valencia-cf", name: "Valencia CF", short: "Valencia", abbr: "VAL", crest: "https://media.api-sports.io/football/teams/532.png", rep: [1, 1, 3] },
    { id: "villarreal-cf", name: "Villarreal CF", short: "Villarreal", abbr: "VIL", crest: "https://media.api-sports.io/football/teams/533.png", rep: [1, 1, 3] },
    { id: "ud-las-palmas", name: "UD Las Palmas", short: "Las Palmas", abbr: "PAL", crest: "https://media.api-sports.io/football/teams/534.png", rep: [0, 0, 1] },
    { id: "sevilla-fc", name: "Sevilla FC", short: "Sevilla", abbr: "SEV", crest: "https://media.api-sports.io/football/teams/536.png", rep: [1, 1, 3] },
    { id: "celta-de-vigo", name: "Celta de Vigo", short: "Celta de Vigo", abbr: "CEL", crest: "https://media.api-sports.io/football/teams/538.png", rep: [1, 0, 3] },
    { id: "real-madrid", name: "Real Madrid", short: "Real Madrid", abbr: "REA", crest: "https://media.api-sports.io/football/teams/541.png", rep: [4, 5, 5] },
    { id: "deportivo-alaves", name: "Deportivo Alavés", short: "Deportivo Alavés", abbr: "ALA", crest: "https://media.api-sports.io/football/teams/542.png", rep: [0, 0, 2] },
    { id: "real-betis", name: "Real Betis", short: "Real Betis", abbr: "BET", crest: "https://media.api-sports.io/football/teams/543.png", rep: [1, 1, 3] },
    { id: "getafe-cf", name: "Getafe CF", short: "Getafe", abbr: "GET", crest: "https://media.api-sports.io/football/teams/546.png", rep: [0, 0, 2] },
    { id: "girona-fc", name: "Girona FC", short: "Girona", abbr: "GIR", crest: "https://media.api-sports.io/football/teams/547.png", rep: [0, 0, 3] },
    { id: "real-sociedad", name: "Real Sociedad", short: "Real Sociedad", abbr: "RSO", crest: "https://media.api-sports.io/football/teams/548.png", rep: [1, 1, 3] },
    { id: "granada-cf", name: "Granada CF", short: "Granada", abbr: "GRA", crest: "https://media.api-sports.io/football/teams/715.png", rep: [0, 0, 0] },
    { id: "ud-almeria", name: "UD Almería", short: "Almería", abbr: "ALM", crest: "https://media.api-sports.io/football/teams/723.png", rep: [0, 0, 2] },
    { id: "cadiz-cf", name: "Cádiz CF", short: "Cádiz", abbr: "CAD", crest: "https://media.api-sports.io/football/teams/724.png", rep: [0, 0, 0] },
    { id: "ca-osasuna", name: "CA Osasuna", short: "Osasuna", abbr: "OSA", crest: "https://media.api-sports.io/football/teams/727.png", rep: [0, 0, 2] },
    { id: "rayo-vallecano", name: "Rayo Vallecano", short: "Rayo Vallecano", abbr: "RAY", crest: "https://media.api-sports.io/football/teams/728.png", rep: [0, 0, 2] },
    { id: "rcd-mallorca", name: "RCD Mallorca", short: "Mallorca", abbr: "MAL", crest: "https://media.api-sports.io/football/teams/798.png", rep: [0, 0, 2] },
    ],
  },
  {
    id: "laliga2",
    name: "LaLiga Hypermotion",
    country: "ESP",
    confederation: "UEFA",
    tier: 2,
    cup: "Copa del Rey",
    clubs: [
    { id: "cd-leganes", name: "CD Leganés", short: "Leganés", abbr: "LEG", crest: "https://media.api-sports.io/football/teams/537.png", rep: [0, 0, 0] },
    { id: "levante-ud", name: "Levante UD", short: "Levante", abbr: "LEV", crest: "https://media.api-sports.io/football/teams/539.png", rep: [0, 0, 2] },
    { id: "rcd-espanyol", name: "RCD Espanyol", short: "Espanyol", abbr: "ESP", crest: "https://media.api-sports.io/football/teams/540.png", rep: [1, 0, 3] },
    { id: "sd-eibar", name: "SD Eibar", short: "Eibar", abbr: "EIB", crest: "https://media.api-sports.io/football/teams/545.png", rep: [0, 0, 0] },
    { id: "ad-alcorcon", name: "AD Alcorcón", short: "Alcorcón", abbr: "ALC", crest: "https://media.api-sports.io/football/teams/711.png", rep: [0, 0, 0] },
    { id: "real-oviedo", name: "Real Oviedo", short: "Real Oviedo", abbr: "OVI", crest: "https://media.api-sports.io/football/teams/718.png", rep: [0, 0, 1] },
    { id: "cd-tenerife", name: "CD Tenerife", short: "Tenerife", abbr: "TEN", crest: "https://media.api-sports.io/football/teams/719.png", rep: [0, 0, 0] },
    { id: "real-valladolid", name: "Real Valladolid", short: "Real Valladolid", abbr: "VAL", crest: "https://media.api-sports.io/football/teams/720.png", rep: [0, 0, 1] },
    { id: "albacete-balompie", name: "Albacete Balompié", short: "Albacete Balompié", abbr: "ALB", crest: "https://media.api-sports.io/football/teams/722.png", rep: [0, 0, 0] },
    { id: "sd-huesca", name: "SD Huesca", short: "Huesca", abbr: "HUE", crest: "https://media.api-sports.io/football/teams/726.png", rep: [0, 0, 0] },
    { id: "sporting-de-gijon", name: "Sporting de Gijón", short: "Sporting de Gijón", abbr: "GIJ", crest: "https://media.api-sports.io/football/teams/731.png", rep: [0, 0, 1] },
    { id: "real-zaragoza", name: "Real Zaragoza", short: "Real Zaragoza", abbr: "ZAR", crest: "https://media.api-sports.io/football/teams/732.png", rep: [0, 0, 0] },
    { id: "elche-cf", name: "Elche CF", short: "Elche", abbr: "ELC", crest: "https://media.api-sports.io/football/teams/797.png", rep: [0, 0, 2] },
    { id: "cd-mirandes", name: "CD Mirandés", short: "Mirandés", abbr: "MIR", crest: "https://media.api-sports.io/football/teams/799.png", rep: [0, 0, 0] },
    { id: "racing-de-santander", name: "Racing de Santander", short: "Racing de Santand…", abbr: "SAN", crest: "https://media.api-sports.io/football/teams/4665.png", rep: [0, 0, 2] },
    { id: "fc-cartagena", name: "FC Cartagena", short: "Cartagena", abbr: "CAR", crest: "https://media.api-sports.io/football/teams/5262.png", rep: [0, 0, 0] },
    { id: "fc-andorra", name: "FC Andorra", short: "Andorra", abbr: "FA", crest: "https://media.api-sports.io/football/teams/8157.png", rep: [0, 0, 0] },
    { id: "sd-amorebieta", name: "SD Amorebieta", short: "Amorebieta", abbr: "AMO", crest: "https://media.api-sports.io/football/teams/9380.png", rep: [0, 0, 0] },
    { id: "racing-de-ferrol", name: "Racing de Ferrol", short: "Racing de Ferrol", abbr: "FER", crest: "https://media.api-sports.io/football/teams/9409.png", rep: [0, 0, 2] },
    { id: "burgos-cf", name: "Burgos CF", short: "Burgos", abbr: "BUR", crest: "https://media.api-sports.io/football/teams/9580.png", rep: [0, 0, 0] },
    { id: "villarreal-b", name: "Villarreal B", short: "Villarreal B", abbr: "VIL", crest: "https://media.api-sports.io/football/teams/9595.png", rep: [1, 1, 3] },
    { id: "cd-eldense", name: "CD Eldense", short: "Eldense", abbr: "CE", crest: "https://media.api-sports.io/football/teams/9692.png", rep: [0, 0, 0] },
    ],
  },
  {
    id: "serie-a",
    name: "Serie A",
    country: "ITA",
    confederation: "UEFA",
    tier: 1,
    cup: "Copa Italia",
    clubs: [
    { id: "ss-lazio", name: "SS Lazio", short: "Lazio", abbr: "LAZ", crest: "https://media.api-sports.io/football/teams/487.png", rep: [1, 0, 3] },
    { id: "sassuolo", name: "Sassuolo", short: "Sassuolo", abbr: "SAS", crest: "https://media.api-sports.io/football/teams/488.png", rep: [0, 0, 3] },
    { id: "ac-milan", name: "AC Milan", short: "Milan", abbr: "MIL", crest: "https://media.api-sports.io/football/teams/489.png", rep: [3, 2, 4] },
    { id: "cagliari", name: "Cagliari", short: "Cagliari", abbr: "CAG", crest: "https://media.api-sports.io/football/teams/490.png", rep: [0, 0, 3] },
    { id: "ssc-napoli", name: "SSC Napoli", short: "Napoli", abbr: "NAP", crest: "https://media.api-sports.io/football/teams/492.png", rep: [2, 1, 4] },
    { id: "udinese", name: "Udinese", short: "Udinese", abbr: "UDI", crest: "https://media.api-sports.io/football/teams/494.png", rep: [0, 0, 3] },
    { id: "genoa", name: "Genoa", short: "Genoa", abbr: "GEN", crest: "https://media.api-sports.io/football/teams/495.png", rep: [1, 0, 3] },
    { id: "juventus", name: "Juventus", short: "Juventus", abbr: "JUV", crest: "https://media.api-sports.io/football/teams/496.png", rep: [3, 3, 5] },
    { id: "as-roma", name: "AS Roma", short: "Roma", abbr: "ROM", crest: "https://media.api-sports.io/football/teams/497.png", rep: [1, 1, 4] },
    { id: "atalanta", name: "Atalanta", short: "Atalanta", abbr: "ATA", crest: "https://media.api-sports.io/football/teams/499.png", rep: [1, 1, 4] },
    { id: "bologna", name: "Bologna", short: "Bologna", abbr: "BOL", crest: "https://media.api-sports.io/football/teams/500.png", rep: [1, 0, 3] },
    { id: "fiorentina", name: "Fiorentina", short: "Fiorentina", abbr: "FIO", crest: "https://media.api-sports.io/football/teams/502.png", rep: [1, 0, 3] },
    { id: "torino", name: "Torino", short: "Torino", abbr: "TOR", crest: "https://media.api-sports.io/football/teams/503.png", rep: [0, 0, 3] },
    { id: "hellas-verona", name: "Hellas Verona", short: "Hellas Verona", abbr: "VER", crest: "https://media.api-sports.io/football/teams/504.png", rep: [0, 0, 2] },
    { id: "inter-de-milan", name: "Inter de Milán", short: "Inter de Milán", abbr: "INT", crest: "https://media.api-sports.io/football/teams/505.png", rep: [3, 3, 5] },
    { id: "empoli", name: "Empoli", short: "Empoli", abbr: "EMP", crest: "https://media.api-sports.io/football/teams/511.png", rep: [0, 0, 1] },
    { id: "frosinone", name: "Frosinone", short: "Frosinone", abbr: "FRO", crest: "https://media.api-sports.io/football/teams/512.png", rep: [0, 0, 2] },
    { id: "salernitana", name: "Salernitana", short: "Salernitana", abbr: "SAL", crest: "https://media.api-sports.io/football/teams/514.png", rep: [0, 0, 1] },
    { id: "lecce", name: "Lecce", short: "Lecce", abbr: "LEC", crest: "https://media.api-sports.io/football/teams/867.png", rep: [0, 0, 2] },
    { id: "monza", name: "Monza", short: "Monza", abbr: "MON", crest: "https://media.api-sports.io/football/teams/1579.png", rep: [0, 0, 2] },
    ],
  },
  {
    id: "serie-b",
    name: "Serie B",
    country: "ITA",
    confederation: "UEFA",
    tier: 2,
    cup: "Copa Italia",
    clubs: [
    { id: "sampdoria", name: "Sampdoria", short: "Sampdoria", abbr: "SAM", crest: "https://media.api-sports.io/football/teams/498.png", rep: [0, 0, 0] },
    { id: "ascoli", name: "Ascoli", short: "Ascoli", abbr: "ASC", crest: "https://media.api-sports.io/football/teams/507.png", rep: [0, 0, 0] },
    { id: "bari", name: "Bari", short: "Bari", abbr: "BAR", crest: "https://media.api-sports.io/football/teams/508.png", rep: [0, 0, 0] },
    { id: "cittadella", name: "Cittadella", short: "Cittadella", abbr: "CIT", crest: "https://media.api-sports.io/football/teams/510.png", rep: [0, 0, 0] },
    { id: "spezia", name: "Spezia", short: "Spezia", abbr: "SPE", crest: "https://media.api-sports.io/football/teams/515.png", rep: [0, 0, 0] },
    { id: "ternana", name: "Ternana", short: "Ternana", abbr: "TER", crest: "https://media.api-sports.io/football/teams/516.png", rep: [0, 0, 0] },
    { id: "venezia", name: "Venezia", short: "Venezia", abbr: "VEN", crest: "https://media.api-sports.io/football/teams/517.png", rep: [0, 0, 2] },
    { id: "brescia", name: "Brescia", short: "Brescia", abbr: "BRE", crest: "https://media.api-sports.io/football/teams/518.png", rep: [0, 0, 0] },
    { id: "cremonese", name: "Cremonese", short: "Cremonese", abbr: "CRE", crest: "https://media.api-sports.io/football/teams/520.png", rep: [0, 0, 2] },
    { id: "palermo", name: "Palermo", short: "Palermo", abbr: "PAL", crest: "https://media.api-sports.io/football/teams/522.png", rep: [0, 0, 2] },
    { id: "parma", name: "Parma", short: "Parma", abbr: "PAR", crest: "https://media.api-sports.io/football/teams/523.png", rep: [0, 0, 1] },
    { id: "pisa", name: "Pisa", short: "Pisa", abbr: "PIS", crest: "https://media.api-sports.io/football/teams/801.png", rep: [0, 0, 2] },
    { id: "reggiana", name: "Reggiana", short: "Reggiana", abbr: "REG", crest: "https://media.api-sports.io/football/teams/880.png", rep: [0, 0, 0] },
    { id: "feralpisalo", name: "Feralpisalo", short: "Feralpisalo", abbr: "FER", crest: "https://media.api-sports.io/football/teams/884.png", rep: [0, 0, 2] },
    { id: "como", name: "Como", short: "Como", abbr: "COM", crest: "https://media.api-sports.io/football/teams/895.png", rep: [1, 1, 4] },
    { id: "modena", name: "Modena", short: "Modena", abbr: "MOD", crest: "https://media.api-sports.io/football/teams/899.png", rep: [0, 0, 1] },
    { id: "sudtirol", name: "Sudtirol", short: "Sudtirol", abbr: "SUD", crest: "https://media.api-sports.io/football/teams/1578.png", rep: [0, 0, 0] },
    { id: "catanzaro", name: "Catanzaro", short: "Catanzaro", abbr: "CAT", crest: "https://media.api-sports.io/football/teams/1687.png", rep: [0, 0, 1] },
    { id: "lecco", name: "Lecco", short: "Lecco", abbr: "LEC", crest: "https://media.api-sports.io/football/teams/6379.png", rep: [0, 0, 2] },
    { id: "cosenza", name: "Cosenza", short: "Cosenza", abbr: "NUO", crest: "https://media.api-sports.io/football/teams/10137.png", rep: [0, 0, 0] },
    ],
  },
  {
    id: "bundesliga",
    name: "Bundesliga",
    country: "GER",
    confederation: "UEFA",
    tier: 1,
    cup: "DFB-Pokal",
    clubs: [
    { id: "bayern-de-munich", name: "Bayern de Múnich", short: "Bayern de Múnich", abbr: "BAY", crest: "https://media.api-sports.io/football/teams/157.png", rep: [5, 4, 5] },
    { id: "fortuna-dusseldorf", name: "Fortuna Düsseldorf", short: "Fortuna Düsseldorf", abbr: "DUS", crest: "https://media.api-sports.io/football/teams/158.png", rep: [2, 2, 4] },
    { id: "sc-freiburg", name: "SC Freiburg", short: "Freiburg", abbr: "FRE", crest: "https://media.api-sports.io/football/teams/160.png", rep: [0, 0, 3] },
    { id: "vfl-wolfsburg", name: "VfL Wolfsburg", short: "VfL Wolfsburg", abbr: "WOL", crest: "https://media.api-sports.io/football/teams/161.png", rep: [0, 0, 3] },
    { id: "werder-bremen", name: "Werder Bremen", short: "Werder Bremen", abbr: "WER", crest: "https://media.api-sports.io/football/teams/162.png", rep: [0, 0, 3] },
    { id: "borussia-monchengladbach", name: "Borussia Mönchengladbach", short: "Borussia Möncheng…", abbr: "MOE", crest: "https://media.api-sports.io/football/teams/163.png", rep: [0, 0, 3] },
    { id: "fsv-mainz-05", name: "FSV Mainz 05", short: "FSV Mainz 05", abbr: "MAI", crest: "https://media.api-sports.io/football/teams/164.png", rep: [0, 0, 3] },
    { id: "borussia-dortmund", name: "Borussia Dortmund", short: "Borussia Dortmund", abbr: "DOR", crest: "https://media.api-sports.io/football/teams/165.png", rep: [2, 2, 4] },
    { id: "1899-hoffenheim", name: "1899 Hoffenheim", short: "1899 Hoffenheim", abbr: "HOF", crest: "https://media.api-sports.io/football/teams/167.png", rep: [0, 0, 3] },
    { id: "bayer-leverkusen", name: "Bayer Leverkusen", short: "Bayer Leverkusen", abbr: "BAY", crest: "https://media.api-sports.io/football/teams/168.png", rep: [1, 1, 4] },
    { id: "eintracht-frankfurt", name: "Eintracht Frankfurt", short: "Eintracht Frankfu…", abbr: "EIN", crest: "https://media.api-sports.io/football/teams/169.png", rep: [1, 1, 3] },
    { id: "fc-augsburg", name: "FC Augsburg", short: "Augsburg", abbr: "AUG", crest: "https://media.api-sports.io/football/teams/170.png", rep: [0, 0, 3] },
    { id: "vfb-stuttgart", name: "VfB Stuttgart", short: "VfB Stuttgart", abbr: "STU", crest: "https://media.api-sports.io/football/teams/172.png", rep: [1, 1, 4] },
    { id: "rb-leipzig", name: "RB Leipzig", short: "RB Leipzig", abbr: "LEI", crest: "https://media.api-sports.io/football/teams/173.png", rep: [1, 1, 4] },
    { id: "vfl-bochum", name: "VfL Bochum", short: "VfL Bochum", abbr: "BOC", crest: "https://media.api-sports.io/football/teams/176.png", rep: [0, 0, 0] },
    { id: "1-fc-heidenheim", name: "1. FC Heidenheim", short: "1. FC Heidenheim", abbr: "HEI", crest: "https://media.api-sports.io/football/teams/180.png", rep: [0, 0, 1] },
    { id: "sv-darmstadt-98", name: "SV Darmstadt 98", short: "SV Darmstadt 98", abbr: "DAR", crest: "https://media.api-sports.io/football/teams/181.png", rep: [0, 0, 0] },
    { id: "union-berlin", name: "Union Berlin", short: "Union Berlin", abbr: "UNI", crest: "https://media.api-sports.io/football/teams/182.png", rep: [0, 0, 3] },
    { id: "1-fc-colonia", name: "1. FC Colonia", short: "1. FC Colonia", abbr: "KOL", crest: "https://media.api-sports.io/football/teams/192.png", rep: [0, 0, 3] },
    ],
  },
  {
    id: "bundesliga2",
    name: "2. Bundesliga",
    country: "GER",
    confederation: "UEFA",
    tier: 2,
    cup: "DFB-Pokal",
    clubs: [
    { id: "hertha-bsc", name: "Hertha BSC", short: "Hertha BSC", abbr: "HER", crest: "https://media.api-sports.io/football/teams/159.png", rep: [0, 0, 1] },
    { id: "hannover-96", name: "Hannover 96", short: "Hannover 96", abbr: "HAN", crest: "https://media.api-sports.io/football/teams/166.png", rep: [0, 0, 1] },
    { id: "1-fc-nurnberg", name: "1. FC Nürnberg", short: "1. FC Nürnberg", abbr: "NUR", crest: "https://media.api-sports.io/football/teams/171.png", rep: [0, 0, 1] },
    { id: "fc-schalke-04", name: "FC Schalke 04", short: "Schalke 04", abbr: "SCH", crest: "https://media.api-sports.io/football/teams/174.png", rep: [0, 0, 2] },
    { id: "hamburger-sv", name: "Hamburger SV", short: "Hamburger SV", abbr: "HAM", crest: "https://media.api-sports.io/football/teams/175.png", rep: [0, 0, 2] },
    { id: "ssv-jahn-regensburg", name: "SSV Jahn Regensburg", short: "SSV Jahn Regensbu…", abbr: "REG", crest: "https://media.api-sports.io/football/teams/177.png", rep: [0, 0, 0] },
    { id: "spvgg-greuther-furth", name: "SpVgg Greuther Fürth", short: "SpVgg Greuther Fü…", abbr: "GRE", crest: "https://media.api-sports.io/football/teams/178.png", rep: [0, 0, 0] },
    { id: "1-fc-magdeburg", name: "1. FC Magdeburg", short: "1. FC Magdeburg", abbr: "MAG", crest: "https://media.api-sports.io/football/teams/179.png", rep: [0, 0, 0] },
    { id: "sc-paderborn-07", name: "SC Paderborn 07", short: "Paderborn 07", abbr: "PAD", crest: "https://media.api-sports.io/football/teams/185.png", rep: [0, 0, 1] },
    { id: "fc-st-pauli", name: "FC St. Pauli", short: "St. Pauli", abbr: "PAU", crest: "https://media.api-sports.io/football/teams/186.png", rep: [0, 0, 2] },
    { id: "holstein-kiel", name: "Holstein Kiel", short: "Holstein Kiel", abbr: "HOL", crest: "https://media.api-sports.io/football/teams/191.png", rep: [0, 0, 1] },
    { id: "eintracht-braunschweig", name: "Eintracht Braunschweig", short: "Eintracht Braunsc…", abbr: "BRA", crest: "https://media.api-sports.io/football/teams/744.png", rep: [0, 0, 0] },
    { id: "1-fc-kaiserslautern", name: "1. FC Kaiserslautern", short: "1. FC Kaiserslaut…", abbr: "KAI", crest: "https://media.api-sports.io/football/teams/745.png", rep: [0, 0, 1] },
    { id: "karlsruher-sc", name: "Karlsruher SC", short: "Karlsruher", abbr: "KAR", crest: "https://media.api-sports.io/football/teams/785.png", rep: [0, 0, 1] },
    { id: "sv-wehen", name: "SV Wehen", short: "SV Wehen", abbr: "WEH", crest: "https://media.api-sports.io/football/teams/1319.png", rep: [0, 0, 0] },
    { id: "hansa-rostock", name: "Hansa Rostock", short: "Hansa Rostock", abbr: "HAN", crest: "https://media.api-sports.io/football/teams/1321.png", rep: [0, 0, 1] },
    { id: "vfl-osnabruck", name: "VfL Osnabrück", short: "VfL Osnabrück", abbr: "OSN", crest: "https://media.api-sports.io/football/teams/1324.png", rep: [0, 0, 0] },
    { id: "sv-elversberg", name: "SV Elversberg", short: "SV Elversberg", abbr: "ELV", crest: "https://media.api-sports.io/football/teams/1660.png", rep: [0, 0, 1] },
    ],
  },
  {
    id: "ligue-1",
    name: "Ligue 1",
    country: "FRA",
    confederation: "UEFA",
    tier: 1,
    cup: "Copa de Francia",
    clubs: [
    { id: "losc-lille", name: "LOSC Lille", short: "Lille", abbr: "LIL", crest: "https://media.api-sports.io/football/teams/79.png", rep: [1, 0, 3] },
    { id: "olympique-de-lyon", name: "Olympique de Lyon", short: "Olympique de Lyon", abbr: "LYO", crest: "https://media.api-sports.io/football/teams/80.png", rep: [2, 1, 4] },
    { id: "olympique-de-marsella", name: "Olympique de Marsella", short: "Olympique de Mars…", abbr: "MAR", crest: "https://media.api-sports.io/football/teams/81.png", rep: [2, 1, 4] },
    { id: "montpellier-hsc", name: "Montpellier HSC", short: "Montpellier HSC", abbr: "MON", crest: "https://media.api-sports.io/football/teams/82.png", rep: [0, 0, 0] },
    { id: "fc-nantes", name: "FC Nantes", short: "Nantes", abbr: "NAN", crest: "https://media.api-sports.io/football/teams/83.png", rep: [0, 0, 3] },
    { id: "ogc-niza", name: "OGC Niza", short: "Niza", abbr: "NIC", crest: "https://media.api-sports.io/football/teams/84.png", rep: [1, 0, 3] },
    { id: "paris-saint-germain", name: "Paris Saint-Germain", short: "Paris Saint-Germa…", abbr: "PSG", crest: "https://media.api-sports.io/football/teams/85.png", rep: [5, 4, 5] },
    { id: "as-monaco", name: "AS Mónaco", short: "Mónaco", abbr: "MON", crest: "https://media.api-sports.io/football/teams/91.png", rep: [2, 1, 4] },
    { id: "stade-de-reims", name: "Stade de Reims", short: "Stade de Reims", abbr: "REI", crest: "https://media.api-sports.io/football/teams/93.png", rep: [0, 0, 2] },
    { id: "stade-rennais", name: "Stade Rennais", short: "Stade Rennais", abbr: "REN", crest: "https://media.api-sports.io/football/teams/94.png", rep: [1, 0, 2] },
    { id: "rc-estrasburgo", name: "RC Estrasburgo", short: "Estrasburgo", abbr: "STR", crest: "https://media.api-sports.io/football/teams/95.png", rep: [1, 1, 4] },
    { id: "toulouse-fc", name: "Toulouse FC", short: "Toulouse", abbr: "TOU", crest: "https://media.api-sports.io/football/teams/96.png", rep: [1, 0, 3] },
    { id: "fc-lorient", name: "FC Lorient", short: "Lorient", abbr: "LOR", crest: "https://media.api-sports.io/football/teams/97.png", rep: [0, 0, 2] },
    { id: "clermont-foot", name: "Clermont Foot", short: "Clermont Foot", abbr: "CLE", crest: "https://media.api-sports.io/football/teams/99.png", rep: [0, 0, 0] },
    { id: "stade-brestois", name: "Stade Brestois", short: "Stade Brestois", abbr: "BRE", crest: "https://media.api-sports.io/football/teams/106.png", rep: [1, 0, 3] },
    { id: "le-havre-ac", name: "Le Havre AC", short: "Le Havre", abbr: "HAV", crest: "https://media.api-sports.io/football/teams/111.png", rep: [0, 0, 1] },
    { id: "fc-metz", name: "FC Metz", short: "Metz", abbr: "MET", crest: "https://media.api-sports.io/football/teams/112.png", rep: [0, 0, 1] },
    { id: "rc-lens", name: "RC Lens", short: "Lens", abbr: "LEN", crest: "https://media.api-sports.io/football/teams/116.png", rep: [1, 0, 3] },
    { id: "saint-etienne", name: "Saint-Étienne", short: "Saint-Étienne", abbr: "ETI", crest: "https://media.api-sports.io/football/teams/1063.png", rep: [0, 0, 2] },
    ],
  },
  {
    id: "ligue-2",
    name: "Ligue 2",
    country: "FRA",
    confederation: "UEFA",
    tier: 2,
    cup: "Copa de Francia",
    clubs: [
    { id: "angers-sco", name: "Angers SCO", short: "Angers SCO", abbr: "ANG", crest: "https://media.api-sports.io/football/teams/77.png", rep: [0, 0, 2] },
    { id: "girondins-de-burdeos", name: "Girondins de Burdeos", short: "Girondins de Burd…", abbr: "BOR", crest: "https://media.api-sports.io/football/teams/78.png", rep: [0, 0, 2] },
    { id: "amiens", name: "Amiens", short: "Amiens", abbr: "AMI", crest: "https://media.api-sports.io/football/teams/87.png", rep: [0, 0, 0] },
    { id: "sm-caen", name: "SM Caen", short: "SM Caen", abbr: "CAE", crest: "https://media.api-sports.io/football/teams/88.png", rep: [0, 0, 0] },
    { id: "ea-guingamp", name: "EA Guingamp", short: "Guingamp", abbr: "GUI", crest: "https://media.api-sports.io/football/teams/90.png", rep: [0, 0, 0] },
    { id: "ac-ajaccio", name: "AC Ajaccio", short: "Ajaccio", abbr: "AJA", crest: "https://media.api-sports.io/football/teams/98.png", rep: [0, 0, 0] },
    { id: "grenoble", name: "Grenoble", short: "Grenoble", abbr: "GRE", crest: "https://media.api-sports.io/football/teams/101.png", rep: [0, 0, 0] },
    { id: "valenciennes", name: "Valenciennes", short: "Valenciennes", abbr: "VAL", crest: "https://media.api-sports.io/football/teams/105.png", rep: [1, 0, 3] },
    { id: "aj-auxerre", name: "AJ Auxerre", short: "Auxerre", abbr: "AUX", crest: "https://media.api-sports.io/football/teams/108.png", rep: [0, 0, 2] },
    { id: "estac-troyes", name: "ESTAC Troyes", short: "ESTAC Troyes", abbr: "TRO", crest: "https://media.api-sports.io/football/teams/110.png", rep: [0, 0, 1] },
    { id: "paris-fc", name: "Paris FC", short: "Paris", abbr: "PAR", crest: "https://media.api-sports.io/football/teams/114.png", rep: [0, 0, 3] },
    { id: "quevilly", name: "Quevilly", short: "Quevilly", abbr: "QUE", crest: "https://media.api-sports.io/football/teams/431.png", rep: [0, 0, 0] },
    { id: "laval", name: "Laval", short: "Laval", abbr: "LAV", crest: "https://media.api-sports.io/football/teams/433.png", rep: [0, 0, 0] },
    { id: "pau-fc", name: "Pau FC", short: "Pau", abbr: "PAU", crest: "https://media.api-sports.io/football/teams/1297.png", rep: [0, 0, 0] },
    { id: "concarneau", name: "Concarneau", short: "Concarneau", abbr: "CON", crest: "https://media.api-sports.io/football/teams/1300.png", rep: [0, 0, 0] },
    { id: "rodez", name: "Rodez", short: "Rodez", abbr: "ROD", crest: "https://media.api-sports.io/football/teams/1301.png", rep: [0, 0, 0] },
    { id: "dunkerque", name: "Dunkerque", short: "Dunkerque", abbr: "DUN", crest: "https://media.api-sports.io/football/teams/1304.png", rep: [0, 0, 0] },
    { id: "bastia", name: "Bastia", short: "Bastia", abbr: "BAS", crest: "https://media.api-sports.io/football/teams/1305.png", rep: [0, 0, 0] },
    { id: "annecy", name: "Annecy", short: "Annecy", abbr: "ANN", crest: "https://media.api-sports.io/football/teams/3012.png", rep: [0, 0, 0] },
    ],
  },
  {
    id: "eredivisie",
    name: "Eredivisie",
    country: "NED",
    confederation: "UEFA",
    tier: 1,
    cup: "Copa de los Países Bajos",
    clubs: [
    { id: "pec-zwolle", name: "PEC Zwolle", short: "PEC Zwolle", abbr: "ZWO", crest: "https://media.api-sports.io/football/teams/193.png", rep: [0, 0, 0] },
    { id: "ajax", name: "Ajax", short: "Ajax", abbr: "AJA", crest: "https://media.api-sports.io/football/teams/194.png", rep: [3, 2, 3] },
    { id: "excelsior", name: "Excelsior", short: "Excelsior", abbr: "EXC", crest: "https://media.api-sports.io/football/teams/196.png", rep: [0, 0, 0] },
    { id: "psv", name: "PSV", short: "PSV", abbr: "PSV", crest: "https://media.api-sports.io/football/teams/197.png", rep: [3, 2, 3] },
    { id: "ado-den-haag", name: "ADO Den Haag", short: "ADO Den Haag", abbr: "HAA", crest: "https://media.api-sports.io/football/teams/198.png", rep: [0, 0, 0] },
    { id: "de-graafschap", name: "De Graafschap", short: "De Graafschap", abbr: "GRA", crest: "https://media.api-sports.io/football/teams/199.png", rep: [0, 0, 0] },
    { id: "vitesse", name: "Vitesse", short: "Vitesse", abbr: "VIT", crest: "https://media.api-sports.io/football/teams/200.png", rep: [0, 0, 2] },
    { id: "az-alkmaar", name: "AZ Alkmaar", short: "AZ Alkmaar", abbr: "ALK", crest: "https://media.api-sports.io/football/teams/201.png", rep: [1, 1, 2] },
    { id: "nac-breda", name: "NAC Breda", short: "NAC Breda", abbr: "BRE", crest: "https://media.api-sports.io/football/teams/203.png", rep: [0, 0, 0] },
    { id: "fortuna-sittard", name: "Fortuna Sittard", short: "Fortuna Sittard", abbr: "SIT", crest: "https://media.api-sports.io/football/teams/205.png", rep: [0, 0, 0] },
    { id: "heracles-almelo", name: "Heracles Almelo", short: "Heracles Almelo", abbr: "HER", crest: "https://media.api-sports.io/football/teams/206.png", rep: [0, 0, 1] },
    { id: "fc-utrecht", name: "FC Utrecht", short: "Utrecht", abbr: "UTR", crest: "https://media.api-sports.io/football/teams/207.png", rep: [0, 0, 2] },
    { id: "fc-emmen", name: "FC Emmen", short: "Emmen", abbr: "EMM", crest: "https://media.api-sports.io/football/teams/208.png", rep: [0, 0, 0] },
    { id: "feyenoord", name: "Feyenoord", short: "Feyenoord", abbr: "FEY", crest: "https://media.api-sports.io/football/teams/209.png", rep: [3, 2, 3] },
    { id: "sc-heerenveen", name: "SC Heerenveen", short: "Heerenveen", abbr: "HEE", crest: "https://media.api-sports.io/football/teams/210.png", rep: [0, 0, 1] },
    { id: "fc-dordrecht", name: "FC Dordrecht", short: "Dordrecht", abbr: "DOR", crest: "https://media.api-sports.io/football/teams/409.png", rep: [0, 0, 0] },
    { id: "go-ahead-eagles", name: "Go Ahead Eagles", short: "Go Ahead Eagles", abbr: "EAG", crest: "https://media.api-sports.io/football/teams/410.png", rep: [0, 0, 1] },
    { id: "nec-nijmegen", name: "NEC Nijmegen", short: "NEC Nijmegen", abbr: "NIJ", crest: "https://media.api-sports.io/football/teams/413.png", rep: [0, 0, 1] },
    { id: "roda-jc", name: "Roda JC", short: "Roda JC", abbr: "ROD", crest: "https://media.api-sports.io/football/teams/414.png", rep: [0, 0, 0] },
    { id: "fc-twente", name: "FC Twente", short: "Twente", abbr: "TWE", crest: "https://media.api-sports.io/football/teams/415.png", rep: [0, 0, 2] },
    { id: "fc-volendam", name: "FC Volendam", short: "Volendam", abbr: "VOL", crest: "https://media.api-sports.io/football/teams/416.png", rep: [0, 0, 0] },
    { id: "rkc-waalwijk", name: "RKC Waalwijk", short: "RKC Waalwijk", abbr: "WAA", crest: "https://media.api-sports.io/football/teams/417.png", rep: [0, 0, 0] },
    { id: "almere-city", name: "Almere City", short: "Almere City", abbr: "ALM", crest: "https://media.api-sports.io/football/teams/419.png", rep: [0, 0, 0] },
    { id: "sparta-rotterdam", name: "Sparta Rotterdam", short: "Sparta Rotterdam", abbr: "SPA", crest: "https://media.api-sports.io/football/teams/426.png", rep: [0, 0, 1] },
    ],
  },
  {
    id: "primeira-liga",
    name: "Primeira Liga",
    country: "POR",
    confederation: "UEFA",
    tier: 1,
    cup: "Copa de Portugal",
    clubs: [
    { id: "sl-benfica", name: "SL Benfica", short: "Benfica", abbr: "BEN", crest: "https://media.api-sports.io/football/teams/211.png", rep: [3, 2, 3] },
    { id: "fc-porto", name: "FC Porto", short: "Porto", abbr: "POR", crest: "https://media.api-sports.io/football/teams/212.png", rep: [3, 2, 3] },
    { id: "moreirense-fc", name: "Moreirense FC", short: "Moreirense", abbr: "MOR", crest: "https://media.api-sports.io/football/teams/215.png", rep: [0, 0, 0] },
    { id: "portimonense-sc", name: "Portimonense SC", short: "Portimonense", abbr: "POR", crest: "https://media.api-sports.io/football/teams/216.png", rep: [0, 0, 0] },
    { id: "sc-braga", name: "SC Braga", short: "Braga", abbr: "BRA", crest: "https://media.api-sports.io/football/teams/217.png", rep: [1, 1, 2] },
    { id: "boavista-fc", name: "Boavista FC", short: "Boavista", abbr: "BF", crest: "https://media.api-sports.io/football/teams/222.png", rep: [0, 0, 1] },
    { id: "gd-chaves", name: "GD Chaves", short: "Chaves", abbr: "CHA", crest: "https://media.api-sports.io/football/teams/223.png", rep: [0, 0, 0] },
    { id: "vitoria-de-guimaraes", name: "Vitória de Guimarães", short: "Vitória de Guimar…", abbr: "GUI", crest: "https://media.api-sports.io/football/teams/224.png", rep: [0, 0, 1] },
    { id: "rio-ave-fc", name: "Rio Ave FC", short: "Rio Ave", abbr: "RIO", crest: "https://media.api-sports.io/football/teams/226.png", rep: [0, 0, 1] },
    { id: "sporting-cp", name: "Sporting CP", short: "Sporting CP", abbr: "SPO", crest: "https://media.api-sports.io/football/teams/228.png", rep: [3, 2, 3] },
    { id: "estoril-praia", name: "Estoril Praia", short: "Estoril Praia", abbr: "EST", crest: "https://media.api-sports.io/football/teams/230.png", rep: [0, 0, 0] },
    { id: "sc-farense", name: "SC Farense", short: "Farense", abbr: "FAR", crest: "https://media.api-sports.io/football/teams/231.png", rep: [0, 0, 0] },
    { id: "fc-arouca", name: "FC Arouca", short: "Arouca", abbr: "ARO", crest: "https://media.api-sports.io/football/teams/240.png", rep: [0, 0, 0] },
    { id: "fc-famalicao", name: "FC Famalicão", short: "Famalicão", abbr: "FAM", crest: "https://media.api-sports.io/football/teams/242.png", rep: [0, 0, 0] },
    { id: "gil-vicente", name: "Gil Vicente", short: "Gil Vicente", abbr: "VIC", crest: "https://media.api-sports.io/football/teams/762.png", rep: [0, 0, 0] },
    { id: "fc-vizela", name: "FC Vizela", short: "Vizela", abbr: "VIZ", crest: "https://media.api-sports.io/football/teams/810.png", rep: [0, 0, 0] },
    { id: "casa-pia-ac", name: "Casa Pia AC", short: "Casa Pia", abbr: "CAS", crest: "https://media.api-sports.io/football/teams/4716.png", rep: [0, 0, 0] },
    { id: "estrela-da-amadora", name: "Estrela da Amadora", short: "Estrela da Amadora", abbr: "EDA", crest: "https://media.api-sports.io/football/teams/15130.png", rep: [0, 0, 0] },
    { id: "avs", name: "AVS", short: "AVS", abbr: "AVS", crest: "https://media.api-sports.io/football/teams/21595.png", rep: [0, 0, 0] },
    ],
  },
  {
    id: "liga-mx",
    name: "Liga MX",
    country: "MEX",
    confederation: "CONCACAF",
    tier: 1,
    cup: "Copa MX",
    clubs: [
    { id: "chivas-de-guadalajara", name: "Chivas de Guadalajara", short: "Chivas de Guadala…", abbr: "GUA", crest: "https://media.api-sports.io/football/teams/2278.png", rep: [3, 3, 3] },
    { id: "tigres-uanl", name: "Tigres UANL", short: "Tigres UANL", abbr: "UAN", crest: "https://media.api-sports.io/football/teams/2279.png", rep: [3, 3, 3] },
    { id: "club-tijuana", name: "Club Tijuana", short: "Club Tijuana", abbr: "CLU", crest: "https://media.api-sports.io/football/teams/2280.png", rep: [1, 1, 2] },
    { id: "toluca", name: "Toluca", short: "Toluca", abbr: "TOL", crest: "https://media.api-sports.io/football/teams/2281.png", rep: [3, 3, 3] },
    { id: "monterrey", name: "Monterrey", short: "Monterrey", abbr: "MON", crest: "https://media.api-sports.io/football/teams/2282.png", rep: [2, 2, 2] },
    { id: "atlas", name: "Atlas", short: "Atlas", abbr: "ATL", crest: "https://media.api-sports.io/football/teams/2283.png", rep: [1, 1, 1] },
    { id: "santos-laguna", name: "Santos Laguna", short: "Santos Laguna", abbr: "SAN", crest: "https://media.api-sports.io/football/teams/2285.png", rep: [2, 2, 1] },
    { id: "pumas-unam", name: "Pumas UNAM", short: "Pumas UNAM", abbr: "UNA", crest: "https://media.api-sports.io/football/teams/2286.png", rep: [2, 2, 2] },
    { id: "club-america", name: "Club América", short: "Club América", abbr: "CLU", crest: "https://media.api-sports.io/football/teams/2287.png", rep: [3, 3, 3] },
    { id: "necaxa", name: "Necaxa", short: "Necaxa", abbr: "NEC", crest: "https://media.api-sports.io/football/teams/2288.png", rep: [1, 1, 1] },
    { id: "club-leon", name: "Club León", short: "Club León", abbr: "CLU", crest: "https://media.api-sports.io/football/teams/2289.png", rep: [2, 2, 2] },
    { id: "queretaro", name: "Querétaro", short: "Querétaro", abbr: "QUE", crest: "https://media.api-sports.io/football/teams/2290.png", rep: [0, 0, 0] },
    { id: "puebla", name: "Puebla", short: "Puebla", abbr: "PUE", crest: "https://media.api-sports.io/football/teams/2291.png", rep: [0, 0, 0] },
    { id: "cf-pachuca", name: "CF Pachuca", short: "Pachuca", abbr: "PAC", crest: "https://media.api-sports.io/football/teams/2292.png", rep: [2, 2, 2] },
    { id: "cruz-azul", name: "Cruz Azul", short: "Cruz Azul", abbr: "CRU", crest: "https://media.api-sports.io/football/teams/2295.png", rep: [3, 3, 3] },
    { id: "fc-juarez", name: "FC Juárez", short: "Juárez", abbr: "FJ", crest: "https://media.api-sports.io/football/teams/2298.png", rep: [1, 1, 1] },
    { id: "atletico-de-san-luis", name: "Atlético de San Luis", short: "Atlético de San L…", abbr: "ASL", crest: "https://media.api-sports.io/football/teams/2314.png", rep: [1, 1, 1] },
    { id: "mazatlan-fc", name: "Mazatlán FC", short: "Mazatlán", abbr: "MF", crest: "https://media.api-sports.io/football/teams/14002.png", rep: [1, 1, 1] },
    ],
  },
  {
    id: "brasileirao",
    name: "Brasileirão",
    country: "BRA",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa de Brasil",
    clubs: [
    { id: "ec-bahia", name: "EC Bahia", short: "Bahia", abbr: "BAH", crest: "https://media.api-sports.io/football/teams/118.png", rep: [1, 1, 2] },
    { id: "internacional", name: "Internacional", short: "Internacional", abbr: "INT", crest: "https://media.api-sports.io/football/teams/119.png", rep: [2, 2, 2] },
    { id: "botafogo", name: "Botafogo", short: "Botafogo", abbr: "BOT", crest: "https://media.api-sports.io/football/teams/120.png", rep: [2, 2, 3] },
    { id: "palmeiras", name: "Palmeiras", short: "Palmeiras", abbr: "PAL", crest: "https://media.api-sports.io/football/teams/121.png", rep: [3, 4, 3] },
    { id: "fluminense", name: "Fluminense", short: "Fluminense", abbr: "FLU", crest: "https://media.api-sports.io/football/teams/124.png", rep: [2, 2, 3] },
    { id: "america-mineiro", name: "América Mineiro", short: "América Mineiro", abbr: "AME", crest: "https://media.api-sports.io/football/teams/125.png", rep: [1, 1, 2] },
    { id: "sao-paulo", name: "São Paulo", short: "São Paulo", abbr: "SAO", crest: "https://media.api-sports.io/football/teams/126.png", rep: [2, 2, 2] },
    { id: "flamengo", name: "Flamengo", short: "Flamengo", abbr: "FLA", crest: "https://media.api-sports.io/football/teams/127.png", rep: [3, 4, 3] },
    { id: "santos", name: "Santos", short: "Santos", abbr: "SAN", crest: "https://media.api-sports.io/football/teams/128.png", rep: [2, 1, 3] },
    { id: "gremio", name: "Grêmio", short: "Grêmio", abbr: "GRE", crest: "https://media.api-sports.io/football/teams/130.png", rep: [2, 2, 3] },
    { id: "corinthians", name: "Corinthians", short: "Corinthians", abbr: "COR", crest: "https://media.api-sports.io/football/teams/131.png", rep: [2, 3, 3] },
    { id: "vasco-da-gama", name: "Vasco da Gama", short: "Vasco da Gama", abbr: "VAS", crest: "https://media.api-sports.io/football/teams/133.png", rep: [2, 1, 3] },
    { id: "athletico-paranaense", name: "Athletico Paranaense", short: "Athletico Paranae…", abbr: "ATL", crest: "https://media.api-sports.io/football/teams/134.png", rep: [2, 2, 2] },
    { id: "cruzeiro", name: "Cruzeiro", short: "Cruzeiro", abbr: "CRU", crest: "https://media.api-sports.io/football/teams/135.png", rep: [2, 3, 3] },
    { id: "coritiba", name: "Coritiba", short: "Coritiba", abbr: "COR", crest: "https://media.api-sports.io/football/teams/147.png", rep: [0, 0, 1] },
    { id: "goias", name: "Goiás", short: "Goiás", abbr: "GOI", crest: "https://media.api-sports.io/football/teams/151.png", rep: [0, 0, 0] },
    { id: "fortaleza", name: "Fortaleza", short: "Fortaleza", abbr: "FOR", crest: "https://media.api-sports.io/football/teams/154.png", rep: [1, 0, 1] },
    { id: "red-bull-bragantino", name: "Red Bull Bragantino", short: "Red Bull Braganti…", abbr: "BRA", crest: "https://media.api-sports.io/football/teams/794.png", rep: [1, 1, 2] },
    { id: "atletico-mineiro", name: "Atlético Mineiro", short: "Atlético Mineiro", abbr: "ATL", crest: "https://media.api-sports.io/football/teams/1062.png", rep: [1, 1, 2] },
    { id: "cuiaba", name: "Cuiabá", short: "Cuiabá", abbr: "CUI", crest: "https://media.api-sports.io/football/teams/1193.png", rep: [0, 0, 0] },
    ],
  },
  {
    id: "liga-argentina",
    name: "Liga Profesional",
    country: "ARG",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Argentina",
    clubs: [
    { id: "gimnasia-la-plata", name: "Gimnasia La Plata", short: "Gimnasia La Plata", abbr: "GIM", crest: "https://media.api-sports.io/football/teams/434.png", rep: [0, 0, 0] },
    { id: "river-plate", name: "River Plate", short: "River Plate", abbr: "RIV", crest: "https://media.api-sports.io/football/teams/435.png", rep: [3, 3, 3] },
    { id: "racing-club", name: "Racing Club", short: "Racing Club", abbr: "RAC", crest: "https://media.api-sports.io/football/teams/436.png", rep: [2, 2, 2] },
    { id: "rosario-central", name: "Rosario Central", short: "Rosario Central", abbr: "ROS", crest: "https://media.api-sports.io/football/teams/437.png", rep: [2, 1, 2] },
    { id: "velez-sarsfield", name: "Vélez Sarsfield", short: "Vélez Sarsfield", abbr: "VEL", crest: "https://media.api-sports.io/football/teams/438.png", rep: [1, 1, 1] },
    { id: "godoy-cruz", name: "Godoy Cruz", short: "Godoy Cruz", abbr: "GOD", crest: "https://media.api-sports.io/football/teams/439.png", rep: [0, 0, 0] },
    { id: "belgrano", name: "Belgrano", short: "Belgrano", abbr: "BEL", crest: "https://media.api-sports.io/football/teams/440.png", rep: [1, 0, 1] },
    { id: "union-de-santa-fe", name: "Unión de Santa Fe", short: "Unión de Santa Fe", abbr: "UNI", crest: "https://media.api-sports.io/football/teams/441.png", rep: [0, 0, 1] },
    { id: "defensa-y-justicia", name: "Defensa y Justicia", short: "Defensa y Justicia", abbr: "DEF", crest: "https://media.api-sports.io/football/teams/442.png", rep: [0, 1, 1] },
    { id: "huracan", name: "Huracán", short: "Huracán", abbr: "HUR", crest: "https://media.api-sports.io/football/teams/445.png", rep: [0, 0, 1] },
    { id: "lanus", name: "Lanús", short: "Lanús", abbr: "LAN", crest: "https://media.api-sports.io/football/teams/446.png", rep: [1, 1, 1] },
    { id: "colon", name: "Colón", short: "Colón", abbr: "COL", crest: "https://media.api-sports.io/football/teams/448.png", rep: [0, 0, 0] },
    { id: "banfield", name: "Banfield", short: "Banfield", abbr: "BAN", crest: "https://media.api-sports.io/football/teams/449.png", rep: [0, 0, 0] },
    { id: "estudiantes-de-la-plata", name: "Estudiantes de La Plata", short: "Estudiantes de La…", abbr: "EST", crest: "https://media.api-sports.io/football/teams/450.png", rep: [2, 2, 2] },
    { id: "boca-juniors", name: "Boca Juniors", short: "Boca Juniors", abbr: "BOC", crest: "https://media.api-sports.io/football/teams/451.png", rep: [3, 3, 3] },
    { id: "tigre", name: "Tigre", short: "Tigre", abbr: "TIG", crest: "https://media.api-sports.io/football/teams/452.png", rep: [0, 0, 1] },
    { id: "independiente", name: "Independiente", short: "Independiente", abbr: "IND", crest: "https://media.api-sports.io/football/teams/453.png", rep: [1, 1, 1] },
    { id: "atletico-tucuman", name: "Atlético Tucumán", short: "Atlético Tucumán", abbr: "TUC", crest: "https://media.api-sports.io/football/teams/455.png", rep: [0, 0, 1] },
    { id: "talleres", name: "Talleres", short: "Talleres", abbr: "TAL", crest: "https://media.api-sports.io/football/teams/456.png", rep: [1, 1, 1] },
    { id: "newell-s-old-boys", name: "Newell's Old Boys", short: "Newell's Old Boys", abbr: "NEW", crest: "https://media.api-sports.io/football/teams/457.png", rep: [1, 1, 1] },
    { id: "argentinos-juniors", name: "Argentinos Juniors", short: "Argentinos Juniors", abbr: "ARG", crest: "https://media.api-sports.io/football/teams/458.png", rep: [1, 1, 1] },
    { id: "arsenal-de-sarandi", name: "Arsenal de Sarandí", short: "Arsenal de Sarandí", abbr: "ARS", crest: "https://media.api-sports.io/football/teams/459.png", rep: [0, 0, 0] },
    { id: "san-lorenzo", name: "San Lorenzo", short: "San Lorenzo", abbr: "LOR", crest: "https://media.api-sports.io/football/teams/460.png", rep: [1, 1, 1] },
    { id: "sarmiento", name: "Sarmiento", short: "Sarmiento", abbr: "SAR", crest: "https://media.api-sports.io/football/teams/474.png", rep: [0, 0, 0] },
    { id: "instituto", name: "Instituto", short: "Instituto", abbr: "INS", crest: "https://media.api-sports.io/football/teams/478.png", rep: [0, 0, 0] },
    { id: "platense", name: "Platense", short: "Platense", abbr: "PLA", crest: "https://media.api-sports.io/football/teams/1064.png", rep: [0, 0, 1] },
    { id: "central-cordoba", name: "Central Córdoba", short: "Central Córdoba", abbr: "CC", crest: "https://media.api-sports.io/football/teams/1065.png", rep: [2, 1, 2] },
    { id: "barracas-central", name: "Barracas Central", short: "Barracas Central", abbr: "BAR", crest: "https://media.api-sports.io/football/teams/2432.png", rep: [0, 0, 0] },
    ],
  },
  {
    id: "primera-nacional",
    name: "Primera Nacional",
    country: "ARG",
    confederation: "CONMEBOL",
    tier: 2,
    cup: "Copa Argentina",
    clubs: [
    { id: "patronato", name: "Patronato", short: "Patronato", abbr: "PAT", crest: "https://media.api-sports.io/football/teams/444.png", rep: [0, 0, 0] },
    { id: "chacarita-juniors", name: "Chacarita Juniors", short: "Chacarita Juniors", abbr: "CHA", crest: "https://media.api-sports.io/football/teams/447.png", rep: [0, 0, 0] },
    { id: "temperley", name: "Temperley", short: "Temperley", abbr: "TEM", crest: "https://media.api-sports.io/football/teams/454.png", rep: [0, 0, 0] },
    { id: "san-martin-de-san-juan", name: "San Martín de San Juan", short: "San Martín de San…", abbr: "MAR", crest: "https://media.api-sports.io/football/teams/461.png", rep: [0, 0, 0] },
    { id: "agropecuario", name: "Agropecuario", short: "Agropecuario", abbr: "AGR", crest: "https://media.api-sports.io/football/teams/462.png", rep: [0, 0, 0] },
    { id: "aldosivi", name: "Aldosivi", short: "Aldosivi", abbr: "ALD", crest: "https://media.api-sports.io/football/teams/463.png", rep: [0, 0, 0] },
    { id: "all-boys", name: "All Boys", short: "All Boys", abbr: "BOY", crest: "https://media.api-sports.io/football/teams/464.png", rep: [0, 0, 0] },
    { id: "atletico-de-rafaela", name: "Atlético de Rafaela", short: "Atlético de Rafae…", abbr: "RAF", crest: "https://media.api-sports.io/football/teams/465.png", rep: [0, 0, 0] },
    { id: "mitre", name: "Mitre", short: "Mitre", abbr: "MIT", crest: "https://media.api-sports.io/football/teams/466.png", rep: [0, 0, 0] },
    { id: "brown-de-adrogue", name: "Brown de Adrogué", short: "Brown de Adrogué", abbr: "BRO", crest: "https://media.api-sports.io/football/teams/468.png", rep: [0, 0, 0] },
    { id: "deportivo-moron", name: "Deportivo Morón", short: "Deportivo Morón", abbr: "DEP", crest: "https://media.api-sports.io/football/teams/469.png", rep: [0, 0, 0] },
    { id: "ferro-carril-oeste", name: "Ferro Carril Oeste", short: "Ferro Carril Oeste", abbr: "FER", crest: "https://media.api-sports.io/football/teams/470.png", rep: [0, 0, 0] },
    { id: "flandria", name: "Flandria", short: "Flandria", abbr: "FLA", crest: "https://media.api-sports.io/football/teams/471.png", rep: [1, 1, 1] },
    { id: "guillermo-brown", name: "Guillermo Brown", short: "Guillermo Brown", abbr: "GUI", crest: "https://media.api-sports.io/football/teams/472.png", rep: [0, 0, 0] },
    { id: "independiente-rivadavia", name: "Independiente Rivadavia", short: "Independiente Riv…", abbr: "RIV", crest: "https://media.api-sports.io/football/teams/473.png", rep: [3, 3, 3] },
    { id: "deportivo-riestra", name: "Deportivo Riestra", short: "Deportivo Riestra", abbr: "RIE", crest: "https://media.api-sports.io/football/teams/476.png", rep: [0, 0, 0] },
    { id: "gimnasia-de-jujuy", name: "Gimnasia de Jujuy", short: "Gimnasia de Jujuy", abbr: "GIM", crest: "https://media.api-sports.io/football/teams/479.png", rep: [0, 0, 0] },
    { id: "quilmes", name: "Quilmes", short: "Quilmes", abbr: "QUI", crest: "https://media.api-sports.io/football/teams/480.png", rep: [0, 0, 0] },
    { id: "villa-dalmine", name: "Villa Dálmine", short: "Villa Dálmine", abbr: "DAL", crest: "https://media.api-sports.io/football/teams/481.png", rep: [0, 0, 0] },
    { id: "almagro", name: "Almagro", short: "Almagro", abbr: "ALM", crest: "https://media.api-sports.io/football/teams/482.png", rep: [0, 0, 0] },
    { id: "nueva-chicago", name: "Nueva Chicago", short: "Nueva Chicago", abbr: "NUE", crest: "https://media.api-sports.io/football/teams/484.png", rep: [0, 0, 0] },
    { id: "san-martin-de-tucuman", name: "San Martín de Tucumán", short: "San Martín de Tuc…", abbr: "MAR", crest: "https://media.api-sports.io/football/teams/485.png", rep: [0, 0, 0] },
    { id: "gimnasia-de-mendoza", name: "Gimnasia de Mendoza", short: "Gimnasia de Mendo…", abbr: "GDM", crest: "https://media.api-sports.io/football/teams/1066.png", rep: [0, 0, 1] },
    { id: "defensores-de-belgrano", name: "Defensores de Belgrano", short: "Defensores de Bel…", abbr: "DEF", crest: "https://media.api-sports.io/football/teams/1067.png", rep: [0, 0, 0] },
    { id: "deportivo-madryn", name: "Deportivo Madryn", short: "Deportivo Madryn", abbr: "DM", crest: "https://media.api-sports.io/football/teams/1929.png", rep: [0, 0, 0] },
    { id: "san-telmo", name: "San Telmo", short: "San Telmo", abbr: "TEL", crest: "https://media.api-sports.io/football/teams/1932.png", rep: [0, 0, 0] },
    { id: "estudiantes-de-buenos-aires", name: "Estudiantes de Buenos Aires", short: "Estudiantes de Bu…", abbr: "EST", crest: "https://media.api-sports.io/football/teams/1936.png", rep: [1, 1, 0] },
    { id: "defensores-unidos", name: "Defensores Unidos", short: "Defensores Unidos", abbr: "UNI", crest: "https://media.api-sports.io/football/teams/1945.png", rep: [0, 0, 1] },
    { id: "chaco-for-ever", name: "Chaco For Ever", short: "Chaco For Ever", abbr: "CHA", crest: "https://media.api-sports.io/football/teams/1946.png", rep: [0, 0, 0] },
    { id: "atlanta", name: "Atlanta", short: "Atlanta", abbr: "ATL", crest: "https://media.api-sports.io/football/teams/1948.png", rep: [0, 0, 0] },
    { id: "deportivo-maipu", name: "Deportivo Maipú", short: "Deportivo Maipú", abbr: "DEP", crest: "https://media.api-sports.io/football/teams/1954.png", rep: [0, 0, 0] },
    { id: "racing-de-cordoba", name: "Racing de Córdoba", short: "Racing de Córdoba", abbr: "RAC", crest: "https://media.api-sports.io/football/teams/1957.png", rep: [2, 2, 2] },
    { id: "alvarado", name: "Alvarado", short: "Alvarado", abbr: "ALV", crest: "https://media.api-sports.io/football/teams/1962.png", rep: [0, 0, 0] },
    { id: "tristan-suarez", name: "Tristan Suarez", short: "Tristan Suarez", abbr: "TRI", crest: "https://media.api-sports.io/football/teams/1965.png", rep: [0, 0, 0] },
    { id: "estudiantes-de-rio-cuarto", name: "Estudiantes de Río Cuarto", short: "Estudiantes de Rí…", abbr: "EDR", crest: "https://media.api-sports.io/football/teams/2424.png", rep: [1, 1, 0] },
    { id: "club-atletico-guemes", name: "Club Atlético Güemes", short: "Club Atlético Güe…", abbr: "CAG", crest: "https://media.api-sports.io/football/teams/3969.png", rep: [0, 0, 0] },
    { id: "almirante-brown", name: "Almirante Brown", short: "Almirante Brown", abbr: "ALM", crest: "https://media.api-sports.io/football/teams/8375.png", rep: [0, 0, 0] },
    ],
  },
  {
    id: "primera-chile",
    name: "Primera División de Chile",
    country: "CHI",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Chile",
    clubs: [
    { id: "colo-colo", name: "Colo Colo", short: "Colo Colo", abbr: "COL", crest: "https://media.api-sports.io/football/teams/2315.png", rep: [2, 1, 0] },
    { id: "curico-unido", name: "Curicó Unido", short: "Curicó Unido", abbr: "CUR", crest: "https://media.api-sports.io/football/teams/2316.png", rep: [1, 0, 0] },
    { id: "palestino", name: "Palestino", short: "Palestino", abbr: "PAL", crest: "https://media.api-sports.io/football/teams/2318.png", rep: [1, 0, 0] },
    { id: "o-higgins", name: "O'Higgins", short: "O'Higgins", abbr: "HIG", crest: "https://media.api-sports.io/football/teams/2320.png", rep: [1, 0, 0] },
    { id: "union-espanola", name: "Unión Española", short: "Unión Española", abbr: "ESP", crest: "https://media.api-sports.io/football/teams/2321.png", rep: [1, 0, 0] },
    { id: "universidad-de-chile", name: "Universidad de Chile", short: "Universidad de Ch…", abbr: "CHI", crest: "https://media.api-sports.io/football/teams/2323.png", rep: [2, 1, 0] },
    { id: "everton-de-vina", name: "Everton de Viña", short: "Everton de Viña", abbr: "EVE", crest: "https://media.api-sports.io/football/teams/2325.png", rep: [1, 0, 0] },
    { id: "union-la-calera", name: "Unión La Calera", short: "Unión La Calera", abbr: "UNI", crest: "https://media.api-sports.io/football/teams/2326.png", rep: [1, 0, 0] },
    { id: "huachipato", name: "Huachipato", short: "Huachipato", abbr: "HUA", crest: "https://media.api-sports.io/football/teams/2328.png", rep: [2, 0, 0] },
    { id: "audax-italiano", name: "Audax Italiano", short: "Audax Italiano", abbr: "ITA", crest: "https://media.api-sports.io/football/teams/2329.png", rep: [1, 0, 0] },
    { id: "coquimbo-unido", name: "Coquimbo Unido", short: "Coquimbo Unido", abbr: "COQ", crest: "https://media.api-sports.io/football/teams/2330.png", rep: [2, 0, 0] },
    { id: "cobresal", name: "Cobresal", short: "Cobresal", abbr: "COB", crest: "https://media.api-sports.io/football/teams/2331.png", rep: [1, 0, 0] },
    { id: "magallanes", name: "Magallanes", short: "Magallanes", abbr: "MAG", crest: "https://media.api-sports.io/football/teams/2336.png", rep: [1, 0, 0] },
    { id: "nublense", name: "Ñublense", short: "Ñublense", abbr: "NUB", crest: "https://media.api-sports.io/football/teams/2337.png", rep: [1, 0, 0] },
    { id: "deportes-copiapo", name: "Deportes Copiapó", short: "Deportes Copiapó", abbr: "COP", crest: "https://media.api-sports.io/football/teams/2343.png", rep: [1, 0, 0] },
    { id: "universidad-catolica", name: "Universidad Católica", short: "Universidad Catól…", abbr: "CAT", crest: "https://media.api-sports.io/football/teams/2994.png", rep: [2, 0, 0] },
    ],
  },
  {
    id: "liga-colombia",
    name: "Liga BetPlay",
    country: "COL",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Colombia",
    clubs: [
    { id: "millonarios", name: "Millonarios", short: "Millonarios", abbr: "MIL", crest: "https://media.api-sports.io/football/teams/1125.png", rep: [2, 0, 0] },
    { id: "deportivo-pasto", name: "Deportivo Pasto", short: "Deportivo Pasto", abbr: "PAS", crest: "https://media.api-sports.io/football/teams/1126.png", rep: [1, 0, 0] },
    { id: "deportivo-cali", name: "Deportivo Cali", short: "Deportivo Cali", abbr: "CAL", crest: "https://media.api-sports.io/football/teams/1127.png", rep: [2, 0, 0] },
    { id: "independiente-medellin", name: "Independiente Medellín", short: "Independiente Med…", abbr: "MED", crest: "https://media.api-sports.io/football/teams/1128.png", rep: [2, 0, 0] },
    { id: "envigado", name: "Envigado", short: "Envigado", abbr: "ENV", crest: "https://media.api-sports.io/football/teams/1129.png", rep: [1, 0, 0] },
    { id: "atletico-huila", name: "Atlético Huila", short: "Atlético Huila", abbr: "HUI", crest: "https://media.api-sports.io/football/teams/1130.png", rep: [1, 0, 0] },
    { id: "bucaramanga", name: "Bucaramanga", short: "Bucaramanga", abbr: "BUC", crest: "https://media.api-sports.io/football/teams/1131.png", rep: [1, 0, 0] },
    { id: "boyaca-chico", name: "Boyacá Chicó", short: "Boyacá Chicó", abbr: "CHI", crest: "https://media.api-sports.io/football/teams/1132.png", rep: [1, 0, 0] },
    { id: "jaguares", name: "Jaguares", short: "Jaguares", abbr: "JAG", crest: "https://media.api-sports.io/football/teams/1133.png", rep: [1, 0, 0] },
    { id: "internacional-de-bogota", name: "Internacional de Bogotá", short: "Internacional de…", abbr: "EQU", crest: "https://media.api-sports.io/football/teams/1134.png", rep: [2, 1, 1] },
    { id: "junior", name: "Junior", short: "Junior", abbr: "JUN", crest: "https://media.api-sports.io/football/teams/1135.png", rep: [2, 0, 0] },
    { id: "once-caldas", name: "Once Caldas", short: "Once Caldas", abbr: "ONC", crest: "https://media.api-sports.io/football/teams/1136.png", rep: [1, 0, 0] },
    { id: "atletico-nacional", name: "Atlético Nacional", short: "Atlético Nacional", abbr: "NAC", crest: "https://media.api-sports.io/football/teams/1137.png", rep: [2, 1, 1] },
    { id: "america-de-cali", name: "América de Cali", short: "América de Cali", abbr: "AME", crest: "https://media.api-sports.io/football/teams/1138.png", rep: [2, 0, 0] },
    { id: "santa-fe", name: "Santa Fe", short: "Santa Fe", abbr: "SAN", crest: "https://media.api-sports.io/football/teams/1139.png", rep: [2, 0, 0] },
    { id: "alianza-valledupar", name: "Alianza Valledupar", short: "Alianza Valledupar", abbr: "ALI", crest: "https://media.api-sports.io/football/teams/1141.png", rep: [1, 0, 0] },
    { id: "deportes-tolima", name: "Deportes Tolima", short: "Deportes Tolima", abbr: "DEP", crest: "https://media.api-sports.io/football/teams/1142.png", rep: [1, 0, 0] },
    { id: "aguilas-doradas", name: "Águilas Doradas", short: "Águilas Doradas", abbr: "ITA", crest: "https://media.api-sports.io/football/teams/1144.png", rep: [1, 0, 0] },
    { id: "deportivo-pereira", name: "Deportivo Pereira", short: "Deportivo Pereira", abbr: "PER", crest: "https://media.api-sports.io/football/teams/1462.png", rep: [1, 0, 0] },
    { id: "union-magdalena", name: "Unión Magdalena", short: "Unión Magdalena", abbr: "UNI", crest: "https://media.api-sports.io/football/teams/1465.png", rep: [1, 0, 0] },
    ],
  },
  {
    id: "primera-uruguay",
    name: "Primera División de Uruguay",
    country: "URU",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Uruguay",
    clubs: [
    { id: "penarol", name: "Peñarol", short: "Peñarol", abbr: "PEN", crest: "https://media.api-sports.io/football/teams/2348.png", rep: [4, 1, 1] },
    { id: "defensor-sporting", name: "Defensor Sporting", short: "Defensor Sporting", abbr: "DEF", crest: "https://media.api-sports.io/football/teams/2350.png", rep: [1, 0, 0] },
    { id: "river-plate-de-montevideo", name: "River Plate de Montevideo", short: "River Plate de Mo…", abbr: "RIV", crest: "https://media.api-sports.io/football/teams/2351.png", rep: [1, 0, 0] },
    { id: "danubio", name: "Danubio", short: "Danubio", abbr: "DAN", crest: "https://media.api-sports.io/football/teams/2352.png", rep: [1, 0, 0] },
    { id: "plaza-colonia", name: "Plaza Colonia", short: "Plaza Colonia", abbr: "PC", crest: "https://media.api-sports.io/football/teams/2355.png", rep: [1, 0, 0] },
    { id: "nacional", name: "Nacional", short: "Nacional", abbr: "CLU", crest: "https://media.api-sports.io/football/teams/2356.png", rep: [4, 1, 1] },
    { id: "fenix", name: "Fénix", short: "Fénix", abbr: "FEN", crest: "https://media.api-sports.io/football/teams/2357.png", rep: [1, 0, 0] },
    { id: "liverpool-de-montevideo", name: "Liverpool de Montevideo", short: "Liverpool de Mont…", abbr: "LIV", crest: "https://media.api-sports.io/football/teams/2358.png", rep: [1, 0, 0] },
    { id: "racing-de-montevideo", name: "Racing de Montevideo", short: "Racing de Montevi…", abbr: "RAC", crest: "https://media.api-sports.io/football/teams/2359.png", rep: [1, 0, 0] },
    { id: "montevideo-wanderers", name: "Montevideo Wanderers", short: "Montevideo Wander…", abbr: "WAN", crest: "https://media.api-sports.io/football/teams/2360.png", rep: [1, 0, 0] },
    { id: "boston-river", name: "Boston River", short: "Boston River", abbr: "BR", crest: "https://media.api-sports.io/football/teams/2361.png", rep: [1, 0, 0] },
    { id: "cerro", name: "Cerro", short: "Cerro", abbr: "CER", crest: "https://media.api-sports.io/football/teams/2362.png", rep: [1, 0, 0] },
    { id: "montevideo-city-torque", name: "Montevideo City Torque", short: "Montevideo City T…", abbr: "MCT", crest: "https://media.api-sports.io/football/teams/2365.png", rep: [1, 0, 0] },
    { id: "cerro-largo", name: "Cerro Largo", short: "Cerro Largo", abbr: "CER", crest: "https://media.api-sports.io/football/teams/2369.png", rep: [1, 0, 0] },
    { id: "deportivo-maldonado", name: "Deportivo Maldonado", short: "Deportivo Maldona…", abbr: "DM", crest: "https://media.api-sports.io/football/teams/2370.png", rep: [1, 0, 0] },
    { id: "la-luz", name: "La Luz", short: "La Luz", abbr: "LL", crest: "https://media.api-sports.io/football/teams/18295.png", rep: [1, 0, 0] },
    ],
  },
  {
    id: "primera-paraguay",
    name: "División Profesional",
    country: "PAR",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Paraguay",
    clubs: [
    { id: "guarani", name: "Guaraní", short: "Guaraní", abbr: "GUA", crest: "https://media.api-sports.io/football/teams/1174.png", rep: [2, 0, 0] },
    { id: "nacional-de-asuncion", name: "Nacional de Asunción", short: "Nacional de Asunc…", abbr: "NAC", crest: "https://media.api-sports.io/football/teams/1175.png", rep: [1, 0, 0] },
    { id: "cerro-porteno", name: "Cerro Porteño", short: "Cerro Porteño", abbr: "CER", crest: "https://media.api-sports.io/football/teams/1176.png", rep: [3, 1, 1] },
    { id: "libertad", name: "Libertad", short: "Libertad", abbr: "LIB", crest: "https://media.api-sports.io/football/teams/1179.png", rep: [3, 1, 1] },
    { id: "general-caballero", name: "General Caballero", short: "General Caballero", abbr: "GC", crest: "https://media.api-sports.io/football/teams/1181.png", rep: [1, 0, 0] },
    { id: "olimpia", name: "Olimpia", short: "Olimpia", abbr: "OLI", crest: "https://media.api-sports.io/football/teams/1182.png", rep: [3, 1, 1] },
    { id: "sportivo-luqueno", name: "Sportivo Luqueño", short: "Sportivo Luqueño", abbr: "SPO", crest: "https://media.api-sports.io/football/teams/1183.png", rep: [1, 0, 0] },
    { id: "sportivo-trinidense", name: "Sportivo Trinidense", short: "Sportivo Triniden…", abbr: "ST", crest: "https://media.api-sports.io/football/teams/1187.png", rep: [0, 0, 0] },
    { id: "resistencia", name: "Resistencia", short: "Resistencia", abbr: "RES", crest: "https://media.api-sports.io/football/teams/2135.png", rep: [1, 0, 0] },
    { id: "guairena-fc", name: "Guairena FC", short: "Guairena", abbr: "GF", crest: "https://media.api-sports.io/football/teams/2138.png", rep: [2, 0, 0] },
    { id: "sportivo-ameliano", name: "Sportivo Ameliano", short: "Sportivo Ameliano", abbr: "SA", crest: "https://media.api-sports.io/football/teams/10487.png", rep: [1, 0, 0] },
    { id: "tacuary", name: "Tacuary", short: "Tacuary", abbr: "TAC", crest: "https://media.api-sports.io/football/teams/10491.png", rep: [1, 0, 0] },
    ],
  },
  {
    id: "liga1-peru",
    name: "Liga 1",
    country: "PER",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Perú",
    clubs: [
    { id: "utc-cajamarca", name: "UTC Cajamarca", short: "UTC Cajamarca", abbr: "CAJ", crest: "https://media.api-sports.io/football/teams/2539.png", rep: [1, 0, 0] },
    { id: "universitario", name: "Universitario", short: "Universitario", abbr: "UNI", crest: "https://media.api-sports.io/football/teams/2540.png", rep: [3, 0, 1] },
    { id: "cesar-vallejo", name: "César Vallejo", short: "César Vallejo", abbr: "CES", crest: "https://media.api-sports.io/football/teams/2541.png", rep: [1, 0, 0] },
    { id: "academia-cantolao", name: "Academia Cantolao", short: "Academia Cantolao", abbr: "AC", crest: "https://media.api-sports.io/football/teams/2543.png", rep: [1, 0, 0] },
    { id: "sport-boys", name: "Sport Boys", short: "Sport Boys", abbr: "SPO", crest: "https://media.api-sports.io/football/teams/2544.png", rep: [3, 0, 1] },
    { id: "deportivo-municipal", name: "Deportivo Municipal", short: "Deportivo Municip…", abbr: "MUN", crest: "https://media.api-sports.io/football/teams/2545.png", rep: [3, 0, 1] },
    { id: "sporting-cristal", name: "Sporting Cristal", short: "Sporting Cristal", abbr: "SPO", crest: "https://media.api-sports.io/football/teams/2546.png", rep: [3, 0, 1] },
    { id: "deportivo-binacional", name: "Deportivo Binacional", short: "Deportivo Binacio…", abbr: "BIN", crest: "https://media.api-sports.io/football/teams/2550.png", rep: [1, 0, 0] },
    { id: "carlos-a-mannucci", name: "Carlos A. Mannucci", short: "Carlos A. Mannucci", abbr: "CAR", crest: "https://media.api-sports.io/football/teams/2551.png", rep: [1, 0, 0] },
    { id: "union-comercio", name: "Unión Comercio", short: "Unión Comercio", abbr: "UC", crest: "https://media.api-sports.io/football/teams/2552.png", rep: [3, 0, 1] },
    { id: "alianza-lima", name: "Alianza Lima", short: "Alianza Lima", abbr: "LIM", crest: "https://media.api-sports.io/football/teams/2553.png", rep: [3, 0, 1] },
    { id: "fbc-melgar", name: "FBC Melgar", short: "FBC Melgar", abbr: "MEL", crest: "https://media.api-sports.io/football/teams/2554.png", rep: [1, 0, 0] },
    { id: "sport-huancayo", name: "Sport Huancayo", short: "Sport Huancayo", abbr: "SPO", crest: "https://media.api-sports.io/football/teams/2555.png", rep: [3, 0, 1] },
    { id: "alianza-atletico", name: "Alianza Atlético", short: "Alianza Atlético", abbr: "AA", crest: "https://media.api-sports.io/football/teams/2560.png", rep: [1, 0, 0] },
    { id: "cienciano", name: "Cienciano", short: "Cienciano", abbr: "CIE", crest: "https://media.api-sports.io/football/teams/2562.png", rep: [1, 0, 0] },
    { id: "atletico-grau", name: "Atlético Grau", short: "Atlético Grau", abbr: "AG", crest: "https://media.api-sports.io/football/teams/2564.png", rep: [1, 0, 0] },
    { id: "cusco", name: "Cusco", short: "Cusco", abbr: "CUS", crest: "https://media.api-sports.io/football/teams/10013.png", rep: [1, 0, 0] },
    { id: "adt", name: "ADT", short: "ADT", abbr: "ADT", crest: "https://media.api-sports.io/football/teams/10492.png", rep: [1, 0, 0] },
    { id: "deportivo-garcilaso", name: "Deportivo Garcilaso", short: "Deportivo Garcila…", abbr: "DG", crest: "https://media.api-sports.io/football/teams/20960.png", rep: [1, 0, 0] },
    ],
  },
  {
    id: "ligapro-ecuador",
    name: "LigaPro",
    country: "ECU",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Ecuador",
    clubs: [
    { id: "emelec", name: "Emelec", short: "Emelec", abbr: "EME", crest: "https://media.api-sports.io/football/teams/1148.png", rep: [3, 1, 1] },
    { id: "delfin-sc", name: "Delfín SC", short: "Delfín", abbr: "DS", crest: "https://media.api-sports.io/football/teams/1149.png", rep: [1, 0, 0] },
    { id: "el-nacional", name: "El Nacional", short: "El Nacional", abbr: "NAC", crest: "https://media.api-sports.io/football/teams/1150.png", rep: [1, 0, 0] },
    { id: "tecnico-universitario", name: "Técnico Universitario", short: "Técnico Universit…", abbr: "TU", crest: "https://media.api-sports.io/football/teams/1151.png", rep: [1, 0, 0] },
    { id: "barcelona-sc", name: "Barcelona SC", short: "Barcelona", abbr: "BAR", crest: "https://media.api-sports.io/football/teams/1152.png", rep: [3, 1, 1] },
    { id: "independiente-del-valle", name: "Independiente del Valle", short: "Independiente del…", abbr: "IND", crest: "https://media.api-sports.io/football/teams/1153.png", rep: [3, 1, 1] },
    { id: "deportivo-cuenca", name: "Deportivo Cuenca", short: "Deportivo Cuenca", abbr: "CUE", crest: "https://media.api-sports.io/football/teams/1154.png", rep: [1, 0, 0] },
    { id: "aucas", name: "Aucas", short: "Aucas", abbr: "AUC", crest: "https://media.api-sports.io/football/teams/1156.png", rep: [1, 0, 0] },
    { id: "universidad-catolica-de-quito", name: "Universidad Católica de Quito", short: "Universidad Catól…", abbr: "UCD", crest: "https://media.api-sports.io/football/teams/1157.png", rep: [1, 0, 0] },
    { id: "ldu-de-quito", name: "LDU de Quito", short: "LDU de Quito", abbr: "QUI", crest: "https://media.api-sports.io/football/teams/1158.png", rep: [3, 1, 1] },
    { id: "guayaquil-city", name: "Guayaquil City", short: "Guayaquil City", abbr: "GC", crest: "https://media.api-sports.io/football/teams/1159.png", rep: [3, 1, 1] },
    { id: "mushuc-runa", name: "Mushuc Runa", short: "Mushuc Runa", abbr: "MUS", crest: "https://media.api-sports.io/football/teams/1162.png", rep: [1, 0, 0] },
    { id: "gualaceo", name: "Gualaceo", short: "Gualaceo", abbr: "GUA", crest: "https://media.api-sports.io/football/teams/1986.png", rep: [1, 0, 0] },
    { id: "orense-sc", name: "Orense SC", short: "Orense", abbr: "OS", crest: "https://media.api-sports.io/football/teams/1992.png", rep: [1, 0, 0] },
    { id: "cumbaya-fc", name: "Cumbayá FC", short: "Cumbayá", abbr: "CF", crest: "https://media.api-sports.io/football/teams/16476.png", rep: [1, 0, 0] },
    { id: "libertad-ecu", name: "Libertad", short: "Libertad", abbr: "LIB", crest: "https://media.api-sports.io/football/teams/18762.png", rep: [1, 0, 0] },
    ],
  },
  {
    id: "primera-bolivia",
    name: "División Profesional",
    country: "BOL",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Bolivia",
    clubs: [
    { id: "aurora", name: "Aurora", short: "Aurora", abbr: "AUR", crest: "https://media.api-sports.io/football/teams/3637.png", rep: [1, 0, 0] },
    { id: "always-ready", name: "Always Ready", short: "Always Ready", abbr: "AR", crest: "https://media.api-sports.io/football/teams/3700.png", rep: [2, 0, 0] },
    { id: "blooming", name: "Blooming", short: "Blooming", abbr: "BLO", crest: "https://media.api-sports.io/football/teams/3701.png", rep: [2, 0, 0] },
    { id: "bolivar", name: "Bolívar", short: "Bolívar", abbr: "BOL", crest: "https://media.api-sports.io/football/teams/3702.png", rep: [2, 0, 0] },
    { id: "guabira", name: "Guabirá", short: "Guabirá", abbr: "GUA", crest: "https://media.api-sports.io/football/teams/3704.png", rep: [1, 0, 0] },
    { id: "jorge-wilstermann", name: "Jorge Wilstermann", short: "Jorge Wilstermann", abbr: "WIL", crest: "https://media.api-sports.io/football/teams/3705.png", rep: [2, 0, 0] },
    { id: "nacional-potosi", name: "Nacional Potosí", short: "Nacional Potosí", abbr: "NAC", crest: "https://media.api-sports.io/football/teams/3706.png", rep: [1, 0, 0] },
    { id: "oriente-petrolero", name: "Oriente Petrolero", short: "Oriente Petrolero", abbr: "ORI", crest: "https://media.api-sports.io/football/teams/3707.png", rep: [2, 0, 0] },
    { id: "royal-pari", name: "Royal Pari", short: "Royal Pari", abbr: "RP", crest: "https://media.api-sports.io/football/teams/3709.png", rep: [1, 0, 0] },
    { id: "the-strongest", name: "The Strongest", short: "The Strongest", abbr: "STR", crest: "https://media.api-sports.io/football/teams/3711.png", rep: [2, 0, 0] },
    { id: "atletico-palmaflor", name: "Atlético Palmaflor", short: "Atlético Palmaflor", abbr: "AP", crest: "https://media.api-sports.io/football/teams/10011.png", rep: [1, 0, 0] },
    { id: "santa-cruz", name: "Santa Cruz", short: "Santa Cruz", abbr: "SAN", crest: "https://media.api-sports.io/football/teams/12259.png", rep: [1, 0, 0] },
    { id: "independiente-petrolero", name: "Independiente Petrolero", short: "Independiente Pet…", abbr: "IP", crest: "https://media.api-sports.io/football/teams/15702.png", rep: [1, 0, 0] },
    { id: "real-tomayapo", name: "Real Tomayapo", short: "Real Tomayapo", abbr: "RT", crest: "https://media.api-sports.io/football/teams/15708.png", rep: [1, 0, 0] },
    { id: "vaca-diez", name: "Vaca Díez", short: "Vaca Díez", abbr: "VD", crest: "https://media.api-sports.io/football/teams/15714.png", rep: [1, 0, 0] },
    { id: "libertad-bol", name: "Libertad", short: "Libertad", abbr: "LIB", crest: "https://media.api-sports.io/football/teams/15715.png", rep: [1, 0, 0] },
    { id: "san-antonio", name: "San Antonio", short: "San Antonio", abbr: "SA", crest: "https://media.api-sports.io/football/teams/17760.png", rep: [1, 0, 0] },
    { id: "universitario-de-vinto", name: "Universitario de Vinto", short: "Universitario de…", abbr: "UDV", crest: "https://media.api-sports.io/football/teams/17762.png", rep: [1, 0, 0] },
    ],
  },
  {
    id: "primera-venezuela",
    name: "Liga FUTVE",
    country: "VEN",
    confederation: "CONMEBOL",
    tier: 1,
    cup: "Copa Venezuela",
    clubs: [
    { id: "zamora-fc", name: "Zamora FC", short: "Zamora", abbr: "ZAM", crest: "https://media.api-sports.io/football/teams/2806.png", rep: [1, 0, 0] },
    { id: "deportivo-tachira", name: "Deportivo Táchira", short: "Deportivo Táchira", abbr: "TAC", crest: "https://media.api-sports.io/football/teams/2807.png", rep: [2, 0, 0] },
    { id: "caracas-fc", name: "Caracas FC", short: "Caracas", abbr: "CAR", crest: "https://media.api-sports.io/football/teams/2808.png", rep: [2, 0, 0] },
    { id: "carabobo-fc", name: "Carabobo FC", short: "Carabobo", abbr: "CAR", crest: "https://media.api-sports.io/football/teams/2810.png", rep: [2, 0, 0] },
    { id: "monagas-sc", name: "Monagas SC", short: "Monagas", abbr: "MS", crest: "https://media.api-sports.io/football/teams/2811.png", rep: [2, 0, 0] },
    { id: "deportivo-la-guaira", name: "Deportivo La Guaira", short: "Deportivo La Guai…", abbr: "LAG", crest: "https://media.api-sports.io/football/teams/2813.png", rep: [2, 0, 0] },
    { id: "portuguesa-fc", name: "Portuguesa FC", short: "Portuguesa", abbr: "PF", crest: "https://media.api-sports.io/football/teams/2814.png", rep: [1, 0, 0] },
    { id: "estudiantes-de-merida", name: "Estudiantes de Mérida", short: "Estudiantes de Mé…", abbr: "EST", crest: "https://media.api-sports.io/football/teams/2818.png", rep: [1, 0, 0] },
    { id: "mineros-de-guayana", name: "Mineros de Guayana", short: "Mineros de Guayana", abbr: "MIN", crest: "https://media.api-sports.io/football/teams/2824.png", rep: [1, 0, 0] },
    { id: "metropolitanos-fc", name: "Metropolitanos FC", short: "Metropolitanos", abbr: "MF", crest: "https://media.api-sports.io/football/teams/2825.png", rep: [2, 0, 0] },
    { id: "puerto-cabello", name: "Puerto Cabello", short: "Puerto Cabello", abbr: "PC", crest: "https://media.api-sports.io/football/teams/2827.png", rep: [2, 0, 0] },
    { id: "angostura-fc", name: "Angostura FC", short: "Angostura", abbr: "AF", crest: "https://media.api-sports.io/football/teams/2838.png", rep: [1, 0, 0] },
    { id: "ucv-fc", name: "UCV FC", short: "UCV", abbr: "UF", crest: "https://media.api-sports.io/football/teams/2840.png", rep: [2, 0, 0] },
    { id: "hermanos-colmenarez", name: "Hermanos Colmenárez", short: "Hermanos Colmenár…", abbr: "HC", crest: "https://media.api-sports.io/football/teams/2854.png", rep: [1, 0, 0] },
    { id: "rayo-zuliano", name: "Rayo Zuliano", short: "Rayo Zuliano", abbr: "RZ", crest: "https://media.api-sports.io/football/teams/16847.png", rep: [1, 0, 0] },
    ],
  },
];
