// ╔══════════════════════════════════════════════════════════════════╗
// ║  Selecciones del Simulador de Carrera                              ║
// ║                                                                    ║
// ║  rep = [continental, mundial, nivel], escala 0-5:                  ║
// ║   · continental → probabilidad de ganar la Eurocopa/Copa América…  ║
// ║   · mundial     → probabilidad de ganar el Mundial                 ║
// ║   · nivel       → el listón para que te convoquen                  ║
// ║                   (ver NATIONAL_CALLUP_BAR en constants.ts)         ║
// ║                                                                    ║
// ║  Las banderas salen de flagcdn.com a partir del código ISO.        ║
// ╚══════════════════════════════════════════════════════════════════╝
import type { CareerCountry } from "./types";

/** 211 selecciones, ordenadas por confederación y nivel. */
export const COUNTRIES: CareerCountry[] = [
  // ── UEFA (55) ──
  { code: "ESP", iso: "es", name: "España", confederation: "UEFA", rep: [4, 5, 5] },
  { code: "FRA", iso: "fr", name: "Francia", confederation: "UEFA", rep: [4, 5, 5] },
  { code: "GER", iso: "de", name: "Alemania", confederation: "UEFA", rep: [3, 4, 5] },
  { code: "ENG", iso: "gb-eng", name: "Inglaterra", confederation: "UEFA", rep: [3, 3, 5] },
  { code: "ITA", iso: "it", name: "Italia", confederation: "UEFA", rep: [3, 3, 5] },
  { code: "NED", iso: "nl", name: "Países Bajos", confederation: "UEFA", rep: [3, 2, 4] },
  { code: "POR", iso: "pt", name: "Portugal", confederation: "UEFA", rep: [3, 2, 4] },
  { code: "BEL", iso: "be", name: "Bélgica", confederation: "UEFA", rep: [2, 1, 3] },
  { code: "CRO", iso: "hr", name: "Croacia", confederation: "UEFA", rep: [2, 1, 3] },
  { code: "AUT", iso: "at", name: "Austria", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "DEN", iso: "dk", name: "Dinamarca", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "SCO", iso: "gb-sct", name: "Escocia", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "WAL", iso: "gb-wls", name: "Gales", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "HUN", iso: "hu", name: "Hungría", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "NOR", iso: "no", name: "Noruega", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "POL", iso: "pl", name: "Polonia", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "RUS", iso: "ru", name: "Rusia", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "SRB", iso: "rs", name: "Serbia", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "SWE", iso: "se", name: "Suecia", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "SUI", iso: "ch", name: "Suiza", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "TUR", iso: "tr", name: "Turquía", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "UKR", iso: "ua", name: "Ucrania", confederation: "UEFA", rep: [1, 0, 2] },
  { code: "ALB", iso: "al", name: "Albania", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "ARM", iso: "am", name: "Armenia", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "AZE", iso: "az", name: "Azerbaiyán", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "BLR", iso: "by", name: "Bielorrusia", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "BIH", iso: "ba", name: "Bosnia-Herzegovina", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "BUL", iso: "bg", name: "Bulgaria", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "CZE", iso: "cz", name: "Chequia", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "SVK", iso: "sk", name: "Eslovaquia", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "SVN", iso: "si", name: "Eslovenia", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "GEO", iso: "ge", name: "Georgia", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "GRE", iso: "gr", name: "Grecia", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "IRL", iso: "ie", name: "Irlanda", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "NIR", iso: "gb-nir", name: "Irlanda del Norte", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "ISL", iso: "is", name: "Islandia", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "KAZ", iso: "kz", name: "Kazajistán", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "MKD", iso: "mk", name: "Macedonia del Norte", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "MNE", iso: "me", name: "Montenegro", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "ROU", iso: "ro", name: "Rumania", confederation: "UEFA", rep: [0, 0, 1] },
  { code: "AND", iso: "ad", name: "Andorra", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "CYP", iso: "cy", name: "Chipre", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "EST", iso: "ee", name: "Estonia", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "FIN", iso: "fi", name: "Finlandia", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "GIB", iso: "gi", name: "Gibraltar", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "FRO", iso: "fo", name: "Islas Feroe", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "ISR", iso: "il", name: "Israel", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "KOS", iso: "xk", name: "Kosovo", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "LVA", iso: "lv", name: "Letonia", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "LIE", iso: "li", name: "Liechtenstein", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "LTU", iso: "lt", name: "Lituania", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "LUX", iso: "lu", name: "Luxemburgo", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "MLT", iso: "mt", name: "Malta", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "MDA", iso: "md", name: "Moldavia", confederation: "UEFA", rep: [0, 0, 0] },
  { code: "SMR", iso: "sm", name: "San Marino", confederation: "UEFA", rep: [0, 0, 0] },
  // ── CONMEBOL (10) ──
  { code: "ARG", iso: "ar", name: "Argentina", confederation: "CONMEBOL", rep: [5, 5, 5] },
  { code: "BRA", iso: "br", name: "Brasil", confederation: "CONMEBOL", rep: [5, 5, 5] },
  { code: "COL", iso: "co", name: "Colombia", confederation: "CONMEBOL", rep: [3, 1, 3] },
  { code: "URU", iso: "uy", name: "Uruguay", confederation: "CONMEBOL", rep: [3, 1, 3] },
  { code: "ECU", iso: "ec", name: "Ecuador", confederation: "CONMEBOL", rep: [1, 0, 2] },
  { code: "PAR", iso: "py", name: "Paraguay", confederation: "CONMEBOL", rep: [1, 0, 2] },
  { code: "CHI", iso: "cl", name: "Chile", confederation: "CONMEBOL", rep: [1, 0, 1] },
  { code: "PER", iso: "pe", name: "Perú", confederation: "CONMEBOL", rep: [1, 0, 1] },
  { code: "BOL", iso: "bo", name: "Bolivia", confederation: "CONMEBOL", rep: [0, 0, 0] },
  { code: "VEN", iso: "ve", name: "Venezuela", confederation: "CONMEBOL", rep: [0, 0, 0] },
  // ── CONCACAF (35) ──
  { code: "USA", iso: "us", name: "Estados Unidos", confederation: "CONCACAF", rep: [5, 3, 1] },
  { code: "MEX", iso: "mx", name: "México", confederation: "CONCACAF", rep: [5, 3, 1] },
  { code: "CAN", iso: "ca", name: "Canadá", confederation: "CONCACAF", rep: [3, 2, 0] },
  { code: "CRC", iso: "cr", name: "Costa Rica", confederation: "CONCACAF", rep: [2, 1, 0] },
  { code: "CUW", iso: "cw", name: "Curazao", confederation: "CONCACAF", rep: [1, 1, 0] },
  { code: "HAI", iso: "ht", name: "Haití", confederation: "CONCACAF", rep: [1, 1, 0] },
  { code: "HON", iso: "hn", name: "Honduras", confederation: "CONCACAF", rep: [1, 1, 0] },
  { code: "JAM", iso: "jm", name: "Jamaica", confederation: "CONCACAF", rep: [1, 1, 0] },
  { code: "PAN", iso: "pa", name: "Panamá", confederation: "CONCACAF", rep: [2, 1, 0] },
  { code: "AIA", iso: "ai", name: "Anguila", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "ATG", iso: "ag", name: "Antigua y Barbuda", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "ARU", iso: "aw", name: "Aruba", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "BAH", iso: "bs", name: "Bahamas", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "BRB", iso: "bb", name: "Barbados", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "BLZ", iso: "bz", name: "Belice", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "BER", iso: "bm", name: "Bermudas", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "CUB", iso: "cu", name: "Cuba", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "DMA", iso: "dm", name: "Dominica", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "SLV", iso: "sv", name: "El Salvador", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "GRN", iso: "gd", name: "Granada", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "GUA", iso: "gt", name: "Guatemala", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "GUY", iso: "gy", name: "Guyana", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "CAY", iso: "ky", name: "Islas Caimán", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "TCA", iso: "tc", name: "Islas Turcas y Caicos", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "VGB", iso: "vg", name: "Islas Vírgenes Británicas", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "VIR", iso: "vi", name: "Islas Vírgenes de EE. UU.", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "MSR", iso: "ms", name: "Montserrat", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "NCA", iso: "ni", name: "Nicaragua", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "PUR", iso: "pr", name: "Puerto Rico", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "DOM", iso: "do", name: "República Dominicana", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "SKN", iso: "kn", name: "San Cristóbal y Nieves", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "VIN", iso: "vc", name: "San Vicente y las Granadinas", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "LCA", iso: "lc", name: "Santa Lucía", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "SUR", iso: "sr", name: "Surinam", confederation: "CONCACAF", rep: [0, 0, 0] },
  { code: "TRI", iso: "tt", name: "Trinidad y Tobago", confederation: "CONCACAF", rep: [0, 0, 0] },
  // ── CAF (54) ──
  { code: "MAR", iso: "ma", name: "Marruecos", confederation: "CAF", rep: [4, 1, 3] },
  { code: "SEN", iso: "sn", name: "Senegal", confederation: "CAF", rep: [4, 1, 3] },
  { code: "ALG", iso: "dz", name: "Argelia", confederation: "CAF", rep: [3, 0, 2] },
  { code: "CMR", iso: "cm", name: "Camerún", confederation: "CAF", rep: [3, 0, 2] },
  { code: "CIV", iso: "ci", name: "Costa de Marfil", confederation: "CAF", rep: [3, 0, 2] },
  { code: "EGY", iso: "eg", name: "Egipto", confederation: "CAF", rep: [3, 0, 2] },
  { code: "NGA", iso: "ng", name: "Nigeria", confederation: "CAF", rep: [3, 0, 2] },
  { code: "BFA", iso: "bf", name: "Burkina Faso", confederation: "CAF", rep: [1, 0, 1] },
  { code: "CPV", iso: "cv", name: "Cabo Verde", confederation: "CAF", rep: [1, 0, 1] },
  { code: "GHA", iso: "gh", name: "Ghana", confederation: "CAF", rep: [2, 0, 1] },
  { code: "MLI", iso: "ml", name: "Mali", confederation: "CAF", rep: [2, 0, 1] },
  { code: "RSA", iso: "za", name: "Sudáfrica", confederation: "CAF", rep: [2, 0, 1] },
  { code: "TUN", iso: "tn", name: "Túnez", confederation: "CAF", rep: [2, 0, 1] },
  { code: "ANG", iso: "ao", name: "Angola", confederation: "CAF", rep: [0, 0, 0] },
  { code: "BEN", iso: "bj", name: "Benín", confederation: "CAF", rep: [0, 0, 0] },
  { code: "BOT", iso: "bw", name: "Botsuana", confederation: "CAF", rep: [0, 0, 0] },
  { code: "BDI", iso: "bi", name: "Burundi", confederation: "CAF", rep: [0, 0, 0] },
  { code: "CHA", iso: "td", name: "Chad", confederation: "CAF", rep: [0, 0, 0] },
  { code: "COM", iso: "km", name: "Comoras", confederation: "CAF", rep: [0, 0, 0] },
  { code: "CGO", iso: "cg", name: "Congo", confederation: "CAF", rep: [0, 0, 0] },
  { code: "ERI", iso: "er", name: "Eritrea", confederation: "CAF", rep: [0, 0, 0] },
  { code: "SWZ", iso: "sz", name: "Esuatini", confederation: "CAF", rep: [0, 0, 0] },
  { code: "ETH", iso: "et", name: "Etiopía", confederation: "CAF", rep: [0, 0, 0] },
  { code: "GAB", iso: "ga", name: "Gabón", confederation: "CAF", rep: [0, 0, 0] },
  { code: "GAM", iso: "gm", name: "Gambia", confederation: "CAF", rep: [0, 0, 0] },
  { code: "GUI", iso: "gn", name: "Guinea", confederation: "CAF", rep: [0, 0, 0] },
  { code: "EQG", iso: "gq", name: "Guinea Ecuatorial", confederation: "CAF", rep: [0, 0, 0] },
  { code: "GNB", iso: "gw", name: "Guinea-Bisáu", confederation: "CAF", rep: [0, 0, 0] },
  { code: "KEN", iso: "ke", name: "Kenia", confederation: "CAF", rep: [0, 0, 0] },
  { code: "LES", iso: "ls", name: "Lesoto", confederation: "CAF", rep: [0, 0, 0] },
  { code: "LBR", iso: "lr", name: "Liberia", confederation: "CAF", rep: [0, 0, 0] },
  { code: "LBY", iso: "ly", name: "Libia", confederation: "CAF", rep: [0, 0, 0] },
  { code: "MAD", iso: "mg", name: "Madagascar", confederation: "CAF", rep: [0, 0, 0] },
  { code: "MWI", iso: "mw", name: "Malaui", confederation: "CAF", rep: [0, 0, 0] },
  { code: "MRI", iso: "mu", name: "Mauricio", confederation: "CAF", rep: [0, 0, 0] },
  { code: "MTN", iso: "mr", name: "Mauritania", confederation: "CAF", rep: [0, 0, 0] },
  { code: "MOZ", iso: "mz", name: "Mozambique", confederation: "CAF", rep: [0, 0, 0] },
  { code: "NAM", iso: "na", name: "Namibia", confederation: "CAF", rep: [0, 0, 0] },
  { code: "NIG", iso: "ne", name: "Níger", confederation: "CAF", rep: [0, 0, 0] },
  { code: "COD", iso: "cd", name: "RD Congo", confederation: "CAF", rep: [2, 0, 0] },
  { code: "CTA", iso: "cf", name: "República Centroafricana", confederation: "CAF", rep: [0, 0, 0] },
  { code: "RWA", iso: "rw", name: "Ruanda", confederation: "CAF", rep: [0, 0, 0] },
  { code: "STP", iso: "st", name: "Santo Tomé y Príncipe", confederation: "CAF", rep: [0, 0, 0] },
  { code: "SEY", iso: "sc", name: "Seychelles", confederation: "CAF", rep: [0, 0, 0] },
  { code: "SLE", iso: "sl", name: "Sierra Leona", confederation: "CAF", rep: [0, 0, 0] },
  { code: "SOM", iso: "so", name: "Somalia", confederation: "CAF", rep: [0, 0, 0] },
  { code: "SDN", iso: "sd", name: "Sudán", confederation: "CAF", rep: [0, 0, 0] },
  { code: "SSD", iso: "ss", name: "Sudán del Sur", confederation: "CAF", rep: [0, 0, 0] },
  { code: "TAN", iso: "tz", name: "Tanzania", confederation: "CAF", rep: [0, 0, 0] },
  { code: "TOG", iso: "tg", name: "Togo", confederation: "CAF", rep: [0, 0, 0] },
  { code: "UGA", iso: "ug", name: "Uganda", confederation: "CAF", rep: [0, 0, 0] },
  { code: "DJI", iso: "dj", name: "Yibuti", confederation: "CAF", rep: [0, 0, 0] },
  { code: "ZAM", iso: "zm", name: "Zambia", confederation: "CAF", rep: [0, 0, 0] },
  { code: "ZIM", iso: "zw", name: "Zimbabue", confederation: "CAF", rep: [0, 0, 0] },
  // ── AFC (46) ──
  { code: "AUS", iso: "au", name: "Australia", confederation: "AFC", rep: [4, 0, 2] },
  { code: "JPN", iso: "jp", name: "Japón", confederation: "AFC", rep: [4, 0, 2] },
  { code: "KSA", iso: "sa", name: "Arabia Saudita", confederation: "AFC", rep: [3, 0, 1] },
  { code: "QAT", iso: "qa", name: "Catar", confederation: "AFC", rep: [3, 0, 1] },
  { code: "KOR", iso: "kr", name: "Corea del Sur", confederation: "AFC", rep: [3, 0, 1] },
  { code: "UAE", iso: "ae", name: "Emiratos Árabes Unidos", confederation: "AFC", rep: [1, 0, 1] },
  { code: "IRQ", iso: "iq", name: "Irak", confederation: "AFC", rep: [2, 0, 1] },
  { code: "IRN", iso: "ir", name: "Irán", confederation: "AFC", rep: [3, 0, 1] },
  { code: "JOR", iso: "jo", name: "Jordania", confederation: "AFC", rep: [1, 0, 1] },
  { code: "UZB", iso: "uz", name: "Uzbekistán", confederation: "AFC", rep: [2, 0, 1] },
  { code: "AFG", iso: "af", name: "Afganistán", confederation: "AFC", rep: [0, 0, 0] },
  { code: "BAN", iso: "bd", name: "Bangladés", confederation: "AFC", rep: [0, 0, 0] },
  { code: "BHR", iso: "bh", name: "Baréin", confederation: "AFC", rep: [0, 0, 0] },
  { code: "BRU", iso: "bn", name: "Brunéi", confederation: "AFC", rep: [0, 0, 0] },
  { code: "BHU", iso: "bt", name: "Bután", confederation: "AFC", rep: [0, 0, 0] },
  { code: "CAM", iso: "kh", name: "Camboya", confederation: "AFC", rep: [0, 0, 0] },
  { code: "CHN", iso: "cn", name: "China", confederation: "AFC", rep: [1, 0, 0] },
  { code: "PRK", iso: "kp", name: "Corea del Norte", confederation: "AFC", rep: [0, 0, 0] },
  { code: "PHI", iso: "ph", name: "Filipinas", confederation: "AFC", rep: [0, 0, 0] },
  { code: "GUM", iso: "gu", name: "Guam", confederation: "AFC", rep: [0, 0, 0] },
  { code: "HKG", iso: "hk", name: "Hong Kong", confederation: "AFC", rep: [0, 0, 0] },
  { code: "IND", iso: "in", name: "India", confederation: "AFC", rep: [0, 0, 0] },
  { code: "IDN", iso: "id", name: "Indonesia", confederation: "AFC", rep: [0, 0, 0] },
  { code: "KGZ", iso: "kg", name: "Kirguistán", confederation: "AFC", rep: [0, 0, 0] },
  { code: "KUW", iso: "kw", name: "Kuwait", confederation: "AFC", rep: [0, 0, 0] },
  { code: "LAO", iso: "la", name: "Laos", confederation: "AFC", rep: [0, 0, 0] },
  { code: "LBN", iso: "lb", name: "Líbano", confederation: "AFC", rep: [0, 0, 0] },
  { code: "MAC", iso: "mo", name: "Macao", confederation: "AFC", rep: [0, 0, 0] },
  { code: "MAS", iso: "my", name: "Malasia", confederation: "AFC", rep: [0, 0, 0] },
  { code: "MDV", iso: "mv", name: "Maldivas", confederation: "AFC", rep: [0, 0, 0] },
  { code: "MNG", iso: "mn", name: "Mongolia", confederation: "AFC", rep: [0, 0, 0] },
  { code: "MYA", iso: "mm", name: "Myanmar", confederation: "AFC", rep: [0, 0, 0] },
  { code: "NEP", iso: "np", name: "Nepal", confederation: "AFC", rep: [0, 0, 0] },
  { code: "OMA", iso: "om", name: "Omán", confederation: "AFC", rep: [0, 0, 0] },
  { code: "PAK", iso: "pk", name: "Pakistán", confederation: "AFC", rep: [0, 0, 0] },
  { code: "PLE", iso: "ps", name: "Palestina", confederation: "AFC", rep: [0, 0, 0] },
  { code: "SIN", iso: "sg", name: "Singapur", confederation: "AFC", rep: [0, 0, 0] },
  { code: "SYR", iso: "sy", name: "Siria", confederation: "AFC", rep: [0, 0, 0] },
  { code: "SRI", iso: "lk", name: "Sri Lanka", confederation: "AFC", rep: [0, 0, 0] },
  { code: "THA", iso: "th", name: "Tailandia", confederation: "AFC", rep: [0, 0, 0] },
  { code: "TPE", iso: "tw", name: "Taiwán", confederation: "AFC", rep: [0, 0, 0] },
  { code: "TJK", iso: "tj", name: "Tayikistán", confederation: "AFC", rep: [0, 0, 0] },
  { code: "TLS", iso: "tl", name: "Timor Oriental", confederation: "AFC", rep: [0, 0, 0] },
  { code: "TKM", iso: "tm", name: "Turkmenistán", confederation: "AFC", rep: [0, 0, 0] },
  { code: "VIE", iso: "vn", name: "Vietnam", confederation: "AFC", rep: [0, 0, 0] },
  { code: "YEM", iso: "ye", name: "Yemen", confederation: "AFC", rep: [0, 0, 0] },
  // ── OFC (11) ──
  { code: "NZL", iso: "nz", name: "Nueva Zelanda", confederation: "OFC", rep: [6, 0, 1] },
  { code: "FIJ", iso: "fj", name: "Fiyi", confederation: "OFC", rep: [0, 0, 0] },
  { code: "COK", iso: "ck", name: "Islas Cook", confederation: "OFC", rep: [0, 0, 0] },
  { code: "SOL", iso: "sb", name: "Islas Salomón", confederation: "OFC", rep: [0, 0, 0] },
  { code: "NCL", iso: "nc", name: "Nueva Caledonia", confederation: "OFC", rep: [0, 0, 0] },
  { code: "PNG", iso: "pw", name: "Palaos", confederation: "OFC", rep: [0, 0, 0] },
  { code: "TAH", iso: "pf", name: "Polinesia Francesa", confederation: "OFC", rep: [0, 0, 0] },
  { code: "SAM", iso: "ws", name: "Samoa", confederation: "OFC", rep: [0, 0, 0] },
  { code: "ASA", iso: "as", name: "Samoa Americana", confederation: "OFC", rep: [0, 0, 0] },
  { code: "TGA", iso: "to", name: "Tonga", confederation: "OFC", rep: [0, 0, 0] },
  { code: "VAN", iso: "vu", name: "Vanuatu", confederation: "OFC", rep: [0, 0, 0] },
];

export const COUNTRY_BY_CODE = new Map(COUNTRIES.map((c) => [c.code, c]));

/** URL de la bandera (flagcdn sirve SVG por código ISO-3166 alpha-2). */
export function flagUrl(country: CareerCountry): string {
  return `https://flagcdn.com/${country.iso}.svg`;
}
